### ISSUE TITLE
There is a potential runtime exception

### ISSUE THREAD

**Issue by Wushuyi123** [stanfordnlp/CoreNLP#1021]
Hello,
First of all i want to thank you for sharing your code. 
But when I was operating some of my files, there was a runtime exception of the type 'java.lang.AssertionError'. The runtime exception was from method: 
**org.restlet.engine.io.IoUtils.delete**
When this method was passed with an unauthorized files/file Not exists, it might cause the program to crash. But the caller may not know these problems and may cause the program to crash suddenly. 
so I suggest you add catch or throw to the source code An exception goes out, which is convenient for the caller to develop. Thank you!
The issue can be reproduced by the following code. 

```
public class Test extends IOUtilsTest{
    public static void main(String[] args) {

        Test test = new Test();
        File file = new File("Any path not exists or unauthorized");
        test.delete(file);
    }

}
```

**Comment by AngledLuffa** [comment]
You aren't meant to use IOUtilsTest routines like this.  They are methods
meant for the test, not part of an API.  Java's File object already has a
delete() method in it which works on single files.  There's a method for
directories, IOUtils.deleteDirRecursively method, but BE VERY CAREFUL
BECAUSE THIS COULD NUKE EVERYTHING.  Also note that if it fails partway,
you'll get a "false" return value and a partially deleted directory
structure.
