### ISSUE TITLE
Coreference on large number of files

### ISSUE THREAD

**Issue by ananyaganesh** [stanfordnlp/CoreNLP#1026]
Hi, this is more of a how-to than an issue. 

I have over 500,000 files on which I'd like to run coreference. I'm passing the input files using a `fileList`, so the pipeline is only getting set up once. I also have the `-threads` option on, and set to 8. Since my files are around 1000 words at least, the neural algorithm seems to be taking ~40-60 seconds per file. 

Is there a way to get this done faster? At the current rate of processing, it could take months if not years for my task to get done.

**Comment by AngledLuffa** [comment]
You can try distributing it on multiple machines.  I don't think there's any specific way to improve the speed or efficiency of that annotator.

**Comment by AngledLuffa** [comment]
You could also try dcoref instead, as I believe that should be faster.

**Comment by J38** [comment]
You can gain a lot of speed up if you use the statistical model with dependency parsing instead (at a small cost of accuracy).  One of the huge coreference bottlenecks is having to use the constituency parser, which the neural model requires, but the statistical model does not necessarily. We are also working on a faster neural model for Stanford CoreNLP 4.1.0 which will work with the dependency parser.

Also, if you want to use the neural parser, you can use the englishSR constituency parser instead which is much faster than than the englishPCFG parser.  But the dependency parsing is even faster.

There is a breakdown here of the speed/accuracy tradeoffs:

https://stanfordnlp.github.io/CoreNLP/coref.html

The `dcoref` annotator is not recommended because it requires the constituency parser as well, which contributes heavily to slowdown.
