### ISSUE TITLE
Unicode characters coreNLP can't handle

### ISSUE THREAD

**Issue by YNedderhoff** [stanfordnlp/CoreNLP#103]
I just tried to use nndep on some social media documents and got errors like 

```java
Nov 15, 2015 5:15:38 PM edu.stanford.nlp.process.PTBLexer next
WARNING: Untokenizable: ? (U+D83D, decimal: 55357)
```

I know that those characters are automatically removed, but I wanted get rid of all those error messages and therefore preprocess the file and remove those characters. Just removing all invalid characters with 

```java
document.replaceAll("[^\\u0009\\u000a\\u000d\\u0020-\\uD7FF\\uE000-\\uFFFD]", "");
```

wasn't enough, the error still occured on some characters, which I then removed with

```java
document.replaceAll("[\\uD83D\\uFFFD\\uFE0F\\u203C\\u3010\\u3011\\u300A\\u166D\\u200C\\u202A\\u202C\\u2049\\u20E3\\u300B\\u300C\\u3030\\u065F\\u0099\\u0F3A\\u0F3B\\uF610\\uFFFC
```

My question is: Is there a complete list of unsupported characters? The ones I removed are just based on my corpus and are not necessarily applicable on another one.

**Comment by irolnick** [comment]
https://mailman.stanford.edu/pipermail/java-nlp-user/2013-May/003539.html

````
TokenizerFactory factory = tlp.getTokenizerFactory();
factory.setOptions("untokenizable=noneDelete")
````

**Comment by YNedderhoff** [comment]
Thank you for your answer. Right now I use the tokenizer by sentence, as documented under API Usage: http://nlp.stanford.edu/software/tokenizer.shtml 

```java
DocumentPreprocessor tokenizer = new DocumentPreprocessor(new StringReader(document));
for (List<HasWord> sentence : tokenizer) {
    // do something with the sentence
```

I don't really see how I would use your example code in this. What is ```tlp```?

**Comment by manning** [comment]
Your code looks right. You need to construct your own TokenizerFactory so you can set options for it. "noneDelete" deletes all unrecognized characters during tokenization and gives no warnings while doing so.  I'm not quite sure what you're wanting instead of that, but the complete set of six options combining whether to log a warning for none, the first, or all, and whether to delete them or to include them as single character tokens in the output: noneDelete, firstDelete, allDelete, noneKeep, firstKeep, allKeep.

You could produce the set of untokenizable characters by running all unicode code points through the tokenizers and seeing how it reacts, but it's not an easy list to characterize, since as well as explicitly mentioned characters in the tokenizer, it recognizes large unicode classes such as "letter" and "digit". For the example you explicitly give, we're currently using jflex-1.5.1, which only handles basic multilingual plane characters, and so is not recognizing a character outside that range. But we will probably soon move to jflex-1.6.1, which can recognize such characters. If they are letters, they will then also immediately be accepted by the tokenizer.

**Comment by YNedderhoff** [comment]
Thank you for your detailed answer. What I was looking for is noneKeep.

**Comment by greeshmasmenon** [comment]
Is there a way to use this with Scala?

**Comment by AngledLuffa** [comment]
Probably, but no one here uses Scala

**Comment by greeshmasmenon** [comment]
Managed to fix this in Scala too. Pasting it here for future reference for others - 

Can be set using the `Properties.setProperty` method.

```
    def createNLPPipeline(): StanfordCoreNLP = {
      val props = new Properties()
      props.put("annotators", "tokenize, ssplit, pos, lemma")
      props.setProperty("tokenize.options", "untokenizable=noneDelete"); // new addition
      new StanfordCoreNLP(props)

```

**Comment by AngledLuffa** [comment]
Thanks for sharing!
