### ISSUE TITLE
NN --> JJR edge not available in JAVA API but shown on corenlp.run - V 4.0.0.

### ISSUE THREAD

**Issue by AdityaSinghChauhan** [stanfordnlp/CoreNLP#1052]
I am trying to parse the following statement : 
"top 5 products having profit greater than 50"

Java Dependency Graph Object has no edges between profit and greater.

![image](https://user-images.githubusercontent.com/12781360/83763322-30aa6500-a696-11ea-9ac6-6255aab4aa0f.png)

But, https://corenlp.run/ shows an edge from profit --> greater (which is desired)

![image](https://user-images.githubusercontent.com/12781360/83763071-ef19ba00-a695-11ea-807f-278c2e1205a7.png)

Version of jar is 4.0.0 and is modified on Apr 26, 2020. 

Code :

`Properties props = new Properties();`
`props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");`
`props.setProperty("coref.algorithm", "neural");`
`props.setProperty("ner.docdate.useFixedDate", new SimpleDateFormat("yyyy-MM-dd").format(new Date()));`
`StanfordCoreNLP pipeline = new StanfordCoreNLP(props);`
`query = "top 5 agents having commission greater than 0.15";`
`CoreDocument document = new CoreDocument(query);`
`pipeline.annotate(document);`
`CoreSentence sentence = document.sentences().get(0);`
`SemanticGraph dependencyParse = sentence.dependencyParse();`

**Comment by AdityaSinghChauhan** [comment]
top 5 agents having commission greater than 0.15

corenlp.run : 
![image](https://user-images.githubusercontent.com/12781360/83764003-01482800-a697-11ea-9d87-d18f836f81b0.png)

java api : 
![image](https://user-images.githubusercontent.com/12781360/83764142-32285d00-a697-11ea-8a60-eb1786b4e698.png)

**Comment by AngledLuffa** [comment]
I believe the issue is that you are using a slightly different model.  corenlp.run is using something specifically labeled "dependency parse" by default, which corresponds to the annotator "depparse".  By using the "parse" model you are first constructing a constituency parse (which is also an option on corenlp.run) and then translating that using a sequence of tree manipulations, rather than doing a direct-to-dependencies parse

Please try that and see if the results are more to your liking.

**Comment by AdityaSinghChauhan** [comment]
Thanks @AngledLuffa . That worked as desired.
