### ISSUE TITLE
how can we invoke this code

### ISSUE THREAD

**Issue by arademaker** [stanfordnlp/CoreNLP#1132]
https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/trees/ud/UniversalEnhancer.java

> Can you give an example of how to invoke it via CoreNLP? It seems to need some kind of embeddings for the gapping component, but I couldn't find documentation explaining how to run it.

Reported in https://github.com/UniversalDependencies/UD_English-EWT/issues/127

**Comment by AngledLuffa** [comment]
There's currently no way to run this separately.  What are you trying to do?

**Comment by AngledLuffa** [comment]
(Obviously you can use the command line tool, but presumably that's not what you're looking for)

**Comment by arademaker** [comment]
Maybe @amir-zeldes can answer. I just help to post the question in the right place. From my side, I would be interested in populate the http://github.com/universaldependencies/UD_Portuguese-Bosque with enhanced dependencies if possible.

**Comment by AngledLuffa** [comment]
Well, if you leave this open, we'll eventually make a general dependency
enhancer available

**Comment by arademaker** [comment]
Sorry, I didn't understand it. So the code is not yet ready? Does it support only English? Comments in https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/trees/ud/UniversalEnhancer.java#L17-L18 suggest that any language is supported.

**Comment by AngledLuffa** [comment]
It can be run on any language.  We just haven't provided a convenient
interface or documentation.

If you don't provide an embeddings file, the embeddings portion will be
skipped.

You do need to provide a relative pronoun regex: in English, something like
that|which|who|whom|whose, but adjusted to be case insensitive.

**Comment by amir-zeldes** [comment]
Thanks for raising this, I'd also be happy if the CoreNLP UD enhancer could be invoked as an independent tool!

@arademaker I also have a DepEdit script for English enhancements which works pretty well, and can be invoked or imported in python. you can see it here:

https://github.com/amir-zeldes/DepEdit/blob/master/examples/eng_enhance.ini

Although it does not address orphan nodes/gapping (for the corpora we build at Georgetown we've been assuming this is handled manually for the few sentences that contain orphan relations).

I think a comprehensive enhancement script will have to be somewhat language dependent, because even if we identify relative pronouns using FEATS, there is currently no universal feature for control behavior - the script can't guess the different xsubj dependency for "Kim promised/forced Lei to go". However I don't think it would be too hard to adapt it to other languages by looking at the parts that refer to specific word forms or xpos values and changing those.

**Comment by AngledLuffa** [comment]
Just to clarify, it can already be run at the command line.  You need to
supply two flags

-conlluFile (treebank to process)
-relativePronouns (a regex which matches that|which|who... in the given
language)

The embeddings are for a particular enhancement which can be skipped

**Comment by AngledLuffa** [comment]
In addition to the existing command line interface, I added a tool which will call it from python, as well.  Should be available with the next release of corenlp & stanza.
