### ISSUE TITLE
Constituent structure to dependency structure: No head rule defined for IP using class edu.stanford.nlp.trees.SemanticHeadFinder

### ISSUE THREAD

**Issue by Dhurim** [stanfordnlp/CoreNLP#1168]
I am trying to convert constituent structure to dependency structure for old English and I was getting the following error 

"No head rule defined for IP using class edu.stanford.nlp.trees.SemanticHeadFinder"

Based on how I understood Parser FAQ, I should be using LeftHeadFinder instead of SemanticHeadFinder. I go at the trees and do this change at EnglishGramaticalStructure and GramaticalStructure. Still somehow it looks for the SemanticHeadFinder. Error point after my changes is edu.stanford.nlp.trees.AbstractCollinsHeadFinder.determineHead(AbstractCollinsHeadFinder.java:193)

Has someone used leftHeadFinder for converting constituent structure to dependency structure, if yes, can you please help me.

**Comment by AngledLuffa** [comment]
At the very least you could send us a copy of the tree or the text which
led to this error...

**Comment by Dhurim** [comment]
Hi John, unfortunately I am not allowed to share the tree file. The error that it shows is the IP rule for a tree starting like this 
(IP
  (NP ( .....
  
Can you help me how to use LeftHeadFinder instead of SemanticHeadFinder. How can I use specifically LeftHeadFinder.

**Comment by AngledLuffa** [comment]
What command line are you using?

**Comment by Dhurim** [comment]
I am using the following command:

`java -cp stanford-corenlp.jar edu.stanford.nlp.trees.EnglishGrammaticalStructure -basic -keepPunct -conllx -treeFile train.clean > ptb_train_3.3.0.sd`

but I have modified the following files:
src/edu/stanford/nlp/trees/EnglishGrammaticalStructure.java replaced SemanticHeadFinder with LeftHeadFinder line 63.

src/edu/stanford/nlp/trees/GrammaticalStructure.java - same thing here line 1092.

But seems I would need to do further changes in order to make it use the leftHeadFinder because of the following line in error
`edu.stanford.nlp.trees.AbstractCollinsHeadFinder.determineNonTrivialHead(AbstractCollinsHeadFinder.java:245)`
but I am not sure how to make semanticHeadFinder false and enable LeftHeadFinder at `AbstractCollinsHeadFinder`

**Comment by AngledLuffa** [comment]
If I take a regular PTB tree and replace the top node with IP, the tree
reader just skips that tree.  That's its own can of worms, BUT, if I can't
reproduce the issue that you're seeing there's no way for me to help you.
If you send us a single tree which reproduces the error, I'll try to help,
and otherwise there's nothing further we can do.

**Comment by Dhurim** [comment]
Thank you very much for trying to help me. I see that I can get a similar tree like mine from the following [link ](https://www-users.york.ac.uk/~lang22/YCOE/doc/annotation/YcoeLite.htm#syntactic_labels) which is public.

Here e.g try to convert this e.g: 
`(IP-MAT (NP-NOM (PRO^N He))(BEPI is)(NP-NOM-PRD (N^N +ende))(PP (P buton)(NP-DAT (Q^D +alcere) (N^D geendunge)))(, .)(CP-ADV (P for) (D^I +don)(C +te)(IP-SUB (NP-NOM (PRO^N he))(BEPI bi+d)(ADVP-TMP (ADV^T +afre))(ADJP-NOM-PRD (ADJ^N ungeendod)))))`

It will bring you to the same error that I am facing.

**Comment by AngledLuffa** [comment]
The tagset is completely different, which means that the conversion rules themselves are not going to work.  For example, take a look at the first rule for pobj:

src/edu/stanford/nlp/trees/EnglishGrammaticalRelations.java line 537

```          
"/^(?:PP(?:-TMP)?|(?:WH)?(?:PP|ADVP))$/ < (SYM|IN|VBG|VBN|TO|FW|RB|RBR $++ (/^(?:WH)?(?:NP|ADJP)(?:-TMP|-ADV)?$/=target !$- @NP) !< /^(?i:not)$/)",
```

It's expecting the preterminals to be PTB tags, and that's completely untrue here.  So assuming `(P for)` is more or less the same thing as `(IN for)`, a possible relation is now lost.  I don't think there's any possible bandaid.  Solutions are 1) remapping all the constituent labels to PTB labels and all the tags to PTB tags, assuming the grammar is even the same as 21st century English, or 2) rewriting all the rules to match the new grammar and the new labels, or 3) build a direct-to-dependency parser, for which we have models in both CoreNLP and stanza.

The point is, I don't think simply switching to a LeftHeadFinder will produce anything useful.

Having said all that, if you want to experiment to see exactly what a flaming pile of poo it becomes, you can see that it is building a HeadFinder in:  GrammaticalStructureConversionUtils.java line 388

Changing that line to use LeftHeadFinder, or changing the underlying EnglishTreebankParserParams to use LeftHeadFinder, ~~works~~ stops crashing for me.  I suppose you could say we never even considered making this an option because of how poorly it performs.

**Comment by AngledLuffa** [comment]
addendum, just to emphasize how badly this will perform: if I do that for the tree you gave me, every single dependency is "dep" except for the one "punct" dependency it's able to extract.
