### ISSUE TITLE
Turn off adding trailing period to abbreviations

### ISSUE THREAD

**Issue by cpuyyp** [stanfordnlp/CoreNLP#1338]
Hello,

I found some examples that the CoreNLP program makes mistakes. Here is the sentence. 
```
One American couple said they took three years to find an agent who could realise their dream of a holiday in the land fabled to be Shangri-La. They were not disappointed.
```
"Shangri-La" from the original text is parsed into three pieces: "Shangri", "-", and **"La."**. But it should be **"La"** without the dot. 

Here is a screenshot of the result from the online server. This issue is also confirmed on my local server.
![image](https://user-images.githubusercontent.com/17038752/217596746-b11bb555-0992-4b69-a9cf-9ff4b8b3d173.png)

More interestingly, after I substitute "La" to be "Lb", the problem still persists. But not after I replace it to be "Lc".

![image](https://user-images.githubusercontent.com/17038752/217600321-44746480-b9d8-41e2-83f8-2144fc85bd81.png)
![image](https://user-images.githubusercontent.com/17038752/217600449-9d6b5a6e-31e5-4cd4-a7d5-8a3f7f315532.png)

I assume this is an error. Could anyone explain or fix it? Thank you so much!!

**Comment by AngledLuffa** [comment]
By way of background, the new tokenization standard (which I hate, for reasons like this thread) is that proper names get split on dashes.

We also have a mechanism where abbreviations such as Mr. get tokenized with the period at the end of the token.  The tokenizer attempts to do this even when the word ends a sentence.

So, since LA and lb are both common abbreviations, the tokenizer first splits Shangri-La into three pieces (again, I hate this), then thinks that La. is an abbreviation ending a sentence, which therefore needs the period attached to it.  The English tokenizer is a DFSA, so there isn't a lot of room for making smarter decisions based on context.  We might be able to add a rule to the DFSA which automatically turns Shangri-La into three tokens and skips the abbreviation processing, but I kind of doubt it, since each existing rule that I see returns a single token for a single span of text.

Put it all together, and unfortunately my conclusion is that unless it turns out Shangri-La is an exception to the hyphen tokenization standard, this bug is effectively not fixable without a major rewrite of the tokenizer.  I'll double check with my PI just to be sure, though.

**Comment by cpuyyp** [comment]
Thanks for the quick and detailed explanation!

I also find several cases that do not involve dashes, such as "Co" becomes "Co." and "Mich" becomes "Mich.".

It's a bit annoying to me that it adds the period. Is there a list of all abbreviations that can trigger this processing? So that I can post-process them back to what they are.

The details below are out of the scope of using CoreNLP, but you may have any suggestions by chance. I appreciate any help you can provide.
I am trying to align tokens from the CoreNLP tokenizer with those from the BERT tokenizer. But both of them have exceptional cases. For example, BERT will tokenize "U.S." into four pieces "U", ".", "S", and ".". And CoreNLP has this period issue. So are there any good ways to align them?

Thank you so much!!

**Comment by AngledLuffa** [comment]
Continuing the investigation, the "tokenize" annotator is composed of two parts here: the deterministic word tokenizer and the deterministic sentence splitter.  (This being a combination is a new change; those used to be separate, but there was no advantage to that.)  If I turn on debug output, the tokens are being created in the way you don't like from the tokenizer before it gets to the sentence splitter...

```
Tokens are: [I, booked, a, ticket, to, Shangri, -, La., .]
```

Looking here:

https://github.com/stanfordnlp/CoreNLP/blob/a8aaaf2002b1ed10b495ee40cd0c5d0aec484ea2/src/edu/stanford/nlp/process/PTBLexer.flex#L552

there should be a `strictAcronym` option which can be turned off to stop this?  It's been a long time, so this is me remembering that something like that existed rather than remembering the pieces themselves.

Digging into that some more, you can set this option in CoreNLP by giving it the flag

`-tokenize.options strictAcronym=true`

so if I run the tokenizer like this:

```
java edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators "tokenize" -ssplit.verbose True -tokenize.options strictAcronym=true
```

I get the desired behavior:

```
Tokens are: [A, beautiful, blue, space, alien, and, I, went, to, Shangri, -, La, .]
```

The only effect `strictAcronym` has is to add the trailing punctuation or not, so I think that's exactly what you're looking for to turn off that behavior.  Just be aware that if you use other annotators, the downstream models were trained on tokens such as `Mr.` rather than `Mr`, so it will likely get those wrong if they show up at the end of sentences.

For the record, the abbreviation stuff is here:

https://github.com/stanfordnlp/CoreNLP/blob/a8aaaf2002b1ed10b495ee40cd0c5d0aec484ea2/src/edu/stanford/nlp/process/PTBLexer.flex#L684

**Comment by cpuyyp** [comment]
Thank you! That's exactly what I needed!
