### ISSUE TITLE
How to run version 3.9.1?

### ISSUE THREAD

**Issue by UntotaufUrlaub** [stanfordnlp/CoreNLP#1358]
Hi :)

How to run the server with version 3.9.1?

I am constrained by another project to this version.

I tried the [download](http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip) from the [history page](https://stanfordnlp.github.io/CoreNLP/history.html). Following the instructions to start the server
`java -mx4g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLPServer -port 9000 -timeout 15000`
results in the following error: `Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP`.
The unzipped download only contains one file, which is named `xom-1.2.10-src.jar.`
My java version is `openjdk version "17.0.7" 2023-04-18`
Starting the server with version 4.5.4 works fine. The downloaded directory containes many more files. Is maybe the download for the old version corrupted?

kind regards

**Comment by AngledLuffa** [comment]
I don't know what happened, especially since my belief is corrupt zip
downloads are useless instead of only having some of the files, but this
link on our history page appears to be the complete 3.9.1 download:

http://nlp.stanford.edu/software/stanford-corenlp-full-2018-02-27.zip

Please note that the current support level for 3.9.1 is "please build a
time machine and ask us 5 years ago"

**Comment by UntotaufUrlaub** [comment]
Thank you for the fast reply.
My download (done with the brave browser) was corrupted. A new download (using firefox) fixed the issue.

Noted.
