### ISSUE TITLE
new requirement in parsers

### ISSUE THREAD

**Issue by Shasetty** [stanfordnlp/CoreNLP#1395]
Hi Sir,
Shankar from Bangalore, India
-----------------------------------------------
Present available parsers are finding grammar relations in the text.
-----------------------------------------------
Can you make the parser, which can find?
1a) solution
2a) problem
2b) requirement
-----------------------------------------------
examples:

1) I found money when cleaning.
money : solution
cleaning : requirement

2) I want to build a bridge.
build : solution
bridge : requirement

3) Fever is not allowing me to work.
fever : problem
work : solution

**Comment by AngledLuffa** [comment]
Each of those sound like a use for dependency attachments, or at least a
model could be built using dependencies.  There's a tool called Semgrex
which allows for searching over dependencies if you come up with some
deterministic rules you want to search for.

Although it's also a little unclear what requirements you're looking for.
In the first sentence, "cleaning" labeled as a requirement doesn't work for
me, since the person could have just said "I found money under the couch"
or "I found money (no explanation)".  At any rate, the thing the person
found would be the obj of found, and where / when / etc would be its obl or
advcl.  (There maybe be other possible dependency connections)

I found money under the couch:  dobj(found, money), obl(found, couch)
I found money when cleaning: dobj(found, money), advcl(found, cleaning)

In the 2nd, if you want to know what a person wants, you would search for
"want", with the xcomp dependency of that being the action they want to do
and the dobj being the target:

I want to build a bridge:  xcomp(want, build), dobj(build, bridge)
I want to cook dinner:  xcomp(want, cook), dobj(cook, dinner)
I want to drink some water:  xcomp(want, drink), dobj(drink, water)

In the 3rd, you could probably come up with a list of words which serve
similar roles, such as "not allowing", "stopping", "preventing", etc...
still, this is a lot more general, I would say, and you'd have been luck
building some kind of model over the dependencies rather than just looking
at the dependencies themselves.  Unfortunately, we don't have such a model,
although it might be on our radar.  There is a sentence classifier in
Stanza which uses constituencies, not dependencies, and that may also serve
a similar role in this case.

The OpenIE annotator gives a bit of an example on how to build a model that
uses dependency structures for slot filling, but in general we don't have a
lot of that available.

**Comment by Shasetty** [comment]
Hi John,
Big Thank you for replying.

-------------------------------------
Although it's also a little unclear what requirements you're looking for.

let me explain my requirements in 2 stages:

2/2 stage
1a) Seeing any text from grammar point of view (sub, verb, obj and others)
1b) let us use these grammar skills in 2nd stage

-----------------------------------------------
1/2 stage

1)To find the real meaning of any text?

we have to:

a1) read them 
a2) analyze them 
a3) understand them
------------------------------------------

2) What are the real challenges in understanding any text?

Taking entire economy (USA or INDIA) as an input.

b1) We are not experts, in all the fields.
b2) Information keeps flowing from all the fields.
-----------------------
C1) informations will be unique
C2) hidden information
C3) indirect information
C4) providing unwanted information
C5) and many more
------------------------------------------

3) Style of available text

d1) Big text with many paragraph
d2) small text with few paragraph
d3) 1 paragraph
d4) 1 liners
d5) single words
------------------------------------------
4) Availability of time
------------------------------------------
5) How to analyze the text to understand the text?

E1) problems are unique
E2) solutions for the problem will be unique

E3) requirements are unique
E4) solution for the requirement will be unique

E5) Decision process will be universal 
--------------------------------------------
6) What is the universal decision process?

Decision process, is looking for;
F1) problem
F2) requirement
----------
F3) solution
----------
F4) path that leads for problem
F5) path that leads for requirement
F6) path that leads for solution
-------------------------------------------------

considering the above inputs , i would like to see the text ,analyze them and understand them as per point 6, and find the main word using parsers(grammar)
