### ISSUE TITLE
Online demo is down

### ISSUE THREAD

**Issue by alpgarcia** [stanfordnlp/CoreNLP#1398]
Hi,

Not sure if this is the right place for this. Please let me know where I should post it instead if needed.

The [online demo](https://corenlp.run/) seems to be down since some days ago (at least). Each time I tried, I got a timeout.

Thanks for your help,
Alberto.

**Comment by AngledLuffa** [comment]
It will.  I just haven't thought about how to prevent the kind of long
queries which were crashing it.  You can thank whoever did that for making
it not available currently

**Comment by melandresen** [comment]
Great, glad to hear that! Thank you!

**Comment by alpgarcia** [comment]
Thanks @mkarmona!

I have the pending task of trying this: https://github.com/stanfordnlp/CoreNLP/issues/1356#issuecomment-1555532571

**Comment by AngledLuffa** [comment]
In general, if you can have your users download external resources, I don't think you need to download all of those pieces yourself.  I could be wrong, though.

For now, I've put the demo back up with a much lower max query length.  If it crashes again, I'll look for other causes.  In the meantime, I do recommend that if people are using the demo for more than just "let's see if CoreNLP can do this thing before we install it and start using it locally", the best approach is to install it and start using it locally.  We just don't have the server capacity to support everyone who might want to use it otherwise.
