### ISSUE TITLE
German Lemma not working?

### ISSUE THREAD

**Issue by GeorgeS2019** [stanfordnlp/CoreNLP#1430]
The provided **StandfordCoreNLP-German.properties**
props.setProperty("annotators", "tokenize, ssplit, mwt, pos, ner, depparse");

Will adding lemma to the properties works?
props.setProperty("annotators", "tokenize, ssplit, mwt, pos, lemma, ner, depparse");

https://github.com/stanfordnlp/CoreNLP/issues/596

I wonder if this has been solved in German

**Comment by GeorgeS2019** [comment]
Found answer:

Lemma only supported in English

![image](https://github.com/stanfordnlp/CoreNLP/assets/49812372/de1352f7-e536-449e-94fd-a634fd351dfe)

**Comment by AngledLuffa** [comment]
Technically a Python lemmatizer could be converted to Java if someone were to implement the seq2seq inference code in Java, but as we have discussed with other annotators that exist for German in Python, there's zero drive to do that for multiple reasons.  If you want to talk with @manning about commissioning such work, please feel free.  Otherwise, there's a lemmatizer in Stanza for German.

https://github.com/stanfordnlp/stanza

**Comment by GeorgeS2019** [comment]
@AngledLuffa 
I am still exploring CoreNLP for German. 
Still at a preliminary stage to explore feasibility. 

Thanks for all feedback. 

Python is great, it is challenging when used in other business use case.

Have you heard of TorchSharp?

**Comment by AngledLuffa** [comment]
I had not, but I have never used C# for anything, so perhaps not surprising

**Comment by GeorgeS2019** [comment]
TorchSharp is attempt to bring PyTorch to c#

We started having so much opposition from the c# community because the syntax is python like but the programming langauge is c#

Therefore it is a best of both worlds

Writing PyTorch like code in c# with all the support of PyTorch community.

We are working towards using TorchSharp to access PyTorch models e.g. HuggingFace

**Comment by GeorgeS2019** [comment]
@AngledLuffa 

Is stanza based on Torch or pytoch?

**Comment by GeorgeS2019** [comment]
> seq2seq inference code

This is a regular code in TorchSharp.

Perhaps using the lemma model in Stanza and doing it in TorchSharp, by passing the CoreNLP in Java, but using CoreNLP in C#

**Comment by AngledLuffa** [comment]
> Is stanza based on Torch or pytorch?

It's Python, using pytorch

> Perhaps using the lemma model in Stanza and doing it in TorchSharp, by passing the CoreNLP in Java, but using CoreNLP in C#

There's a fundamental problem here which is

- no one here uses C# for anything
- even the number of Java projects is very limited.  it's basically me, another research engineer, and our PI who work on this as needed
- everyone here thinks that because Stanza is available for German, with a complete suite of models, there's no point in adding more functionality to the CoreNLP side of things.  the one asterisk being that there is currently no Stanza constituency parser
- if we *did* spend time converting a model such as the lemmatizer to Java, it would not benefit the group in any way (no publications, no citations, no $$) and it would not benefit the individual in any way (seeing as how publications and citations are needed to advance our careers).  therefore no one will ever wake up one day and say "today is the day / week / month to convert the German lemmatizer to Java"

The only ways I see to change this dynamic is to do it yourself, to propose a research project that for some reason needs a German lemmatizer in Java with a high likelihood of being published, or offer our PI to buy a commercial license for CoreNLP specifically with a German lemmatizer.  You are welcome to pursue any of those three options, and otherwise I think we're reaching the limit of what can be accomplished with polite conversation about the limitations of the CoreNLP models for German.

**Comment by GeorgeS2019** [comment]
@AngledLuffa 

Currently not in position related to commercial. 

Imagine, a **smart** German learning app that will help Ukrainian to **speed up their integration**  (by speaking German in record time) in Germany.

This is the direction I could think of. Is there funding that would support this from US?

**Comment by AngledLuffa** [comment]
I mean, there's zero Ukrainian support in CoreNLP and some level of
Ukrainian support in Stanza, so why not use Stanza and get both?
