### ISSUE TITLE
Is downloads.cs.stanford.edu down?

### ISSUE THREAD

**Issue by snc-mana** [stanfordnlp/CoreNLP#1434]
Cannot download http://www-nlp.stanford.edu/pubs/crosswikis-data.tar.bz2

**Comment by AngledLuffa** [comment]
Where was this linked from?  It would seem that the basic problem is not
that the download site is not available, but that the directory doesn't
have an index.html in it and there's no default action to list the files
when presented with a link to the data directory rather than a specific
file.  The solution is either to ask our IT to make browsing the directory
available, or to put a boilerplate index.html on it which links all the
files.  The question I would need answered, though, is how did you get
there?  I think that would inform my figuring out how to make it available
to you via download

**Comment by snc-mana** [comment]
It was found here: https://nlp.stanford.edu/pubs/crosswikis.pdf

It's the 4th footnote.

**Comment by AngledLuffa** [comment]
Gotcha.  In that case, it seems like the easiest thing to do is just compress the entire directory into a new .bz2 file, which I've done.  I'm not sure why it was expanded in the first place.  You should be able to download it now...  LMK if it's what you're looking for.

**Comment by DharahasGoud** [comment]
The solution is either to ask our IT to make browsing the directory
available, or to put a boilerplate index.html on it which links all the
files.  The question I would need answered, though, is how did you get
there?  I think that would inform my figuring out how to make it available
to you via download
