### ISSUE TITLE
Problems with multiple-byte unicodes.

### ISSUE THREAD

**Issue by VikingMew** [stanfordnlp/CoreNLP#162]
io.IOutils.slurpInputStream
line nearby 1347.
amountRead is not equal to the length of chunk.
Will append extra 0 to buff.

**Comment by manning** [comment]
@gangeli: I think that @VikingMew is right and this code is just wrong: amountRead is in bytes but then you use it to take the slice of the CharBuffer in characters. In the only current use of this method (in StanfordCoreNLPServer), you work around this -- uglily -- by converting the nulls to spaces, but....

I don't understand why you need to have this method rather than using the existing methods:

```
return IOUtils.slurpReader(encodedInputStreamReader(is, encoding));
```

Any good reason for not using that?

**Comment by gangeli** [comment]
Fixed; commit coming soon. I was wondering why we got the null byte error in the server, but didn't think to check that the IOUtils method was incorrect (I'm not the author).
