### ISSUE TITLE
embeddingSize is not a command line option in nn depenency parser

### ISSUE THREAD

**Issue by sivareddyg** [stanfordnlp/CoreNLP#164]
I am referring to the line [1184 in DependencyParser.java](https://github.com/stanfordnlp/CoreNLP/blob/172fd0a13beef7e885960571379e9f4a8aa8d08a/src/edu/stanford/nlp/parser/nndep/DependencyParser.java#L1184) 

  `*     <code>java edu.stanford.nlp.parser.nndep.DependencyParser -trainFile trainPath -devFile devPath -embedFile wordEmbeddingFile -embeddingSize wordEmbeddingDimensionality -model modelOutputFile.txt.gz</code>`

embeddingSize is not a commandLine option here (its a config option). Instead it should be specified in the props file.

If you specify an embeddingSize other than 50 in the command line, you will get this error 

`The dimension of embedding file does not match`

Though this is a minor issue, a lot of time can be saved for others. 

Thanks a lot for this great resource!

**Comment by J38** [comment]
Just to clarify about this issue.

`-embeddingSize` specifies the embedding size you want to use.

`-embedFile` specifies the initial file you want to use if you happen to have initial embeddings.

If these don't match you'll get the error you speak of.  For instance if you say you want embeddings of size 300 and provide a file with embeddings of size 50, it will break.

If you provide a file with embeddings of size 300 and set embedding size to 300 it will work fine (I recently did this with Spanish).  

There is a different case where you don't have am embedding file at all, and you might specify 50 or 300 or whatever you want.  So that is the point of the standalone `-embeddingSize` setting.
