### ISSUE TITLE
[OpenIE] - Doesn't work for all sentences

### ISSUE THREAD

**Issue by davidaparicio** [stanfordnlp/CoreNLP#167]
Steps to Reproduce: 
1. Open http://corenlp.run/ demo
2. Set defaults parameters (parts-of-speech, named entities, dependency parse, openie)
3. Put a sentence, like "This movie was my best film of my life"
4. Submit

Actual results
No OpenIE results

Expected results
(movie, be, best film)

**Comment by J38** [comment]
OpenIE is not guaranteed to find a relation in every sentence.  The model at this time is apparently having trouble with "This movie" vs. "The movie".

**Comment by davidaparicio** [comment]
But it's not only with "this".

For example, if I apply OpenIE algorithm on the Sentiment Treebank (http://nlp.stanford.edu/sentiment/treebank.html), it'll fail to find a relation, 3704 times (on 9645 sentences). It's almost 40%..

Like the review "A gripping , searing portrait of a lost soul trying to find her way through life" doesn't give results..

It isn't written on the documentation of OpenIE, the algorithm fails on several classical texts:
- "This product works terribly" /  "I am going to buy this phone" (Word "this" problem)
- "I throw away my laptop"
- "It doesn't work if we think the people who disagree with us are all motivated by malice, or that our political opponents are unpatriotic." (Obama State of the Union speech)
- "Most of all, democracy breaks down when the average person feels their voice doesn't matter; that the system is rigged in favor of the rich or the powerful or some narrow interest."
- "Things don't have to change the world to be important." (Steve Jobs quote)
- "A lot of times, people don't know what they want until you show it to them."

**Comment by gangeli** [comment]
I'll actually take 60% recall as fairly good. There's an inherent tradeoff between precision and recall, and pushing too much on recall hurts precision.

That said, RE your particular examples:

* "I throw away my laptop" -- I've fixed this
* "It doesn't work if we think the people who disagree with us are all motivated by malice, or that our political opponents are unpatriotic." -- This has a negation in it, which is apparently mis-scoped. Negated statements are not extracted by design.
* "Most of all, democracy breaks down when the average person feels their voice doesn't matter; that the system is rigged in favor of the rich or the powerful or some narrow interest." -- I suspect the words "Most" and "all" screw this up, as the system considers them quantifiers. But, more generally, it's unclear what relation should be extracted from this? Perhaps "democracy breaks down"? The part of the sentence after "when" is a hypothetical and shouldn't be extracted by the system.
* "Things don't have to change the world to be important." -- Negation again.
* "A lot of times, people don't know what they want until you show it to them." -- Negation again.
* "This product works terribly" -- This is actually not the "this" problem, but rather the fact that "terribly" is an adverb. Really, this is a unary relation, where "works terribly" is an atomic relation applied to "this product." To illustrate, take the analogous sentence "the boy ate quickly." Clearly it would be incorrect to extract that the boy ate something, and that something was "quickly."
