### ISSUE TITLE
NER requirements

### ISSUE THREAD

**Issue by VitalyShcherb** [stanfordnlp/CoreNLP#173]
Hello, i have question about NER. In "Stanford NER CRF FAQ" (http://nlp.stanford.edu/software/crf-faq.shtml#pos  question 17) is written that NER don't use POS tags by default. But in `edu/stanford/nlp/pipeline/Annotator.java` there are requirements about it.

**Comment by J38** [comment]
It appears to me you need POS tags for SUTime and Numeric stuff.  If you shut those off you can NER tag without the POS tags.

**Comment by manning** [comment]
@j38 is correct. At the moment we don't have accurate enough tracking of requirements to differentiate them by models or options used.

**Comment by gangeli** [comment]
Is this still true now that we're tracking dependencies by Annotations? It looks like we do actually now distinguish between the case where NER needs POS tags or doesn't need POS tags: https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/pipeline/NERCombinerAnnotator.java#L185

The requirements listed in `Annotator` still list POS tags as a requirement, but the requirements there are meant to be an intelligent default rather than something strictly enforced.

**Comment by J38** [comment]
When I look at NERCombinerAnnotator it checks:

    if (ner.usesSUTime() || ner.appliesNumericClassifiers()) {

If either of those passes, it requires POS tags, else it does not.
