### ISSUE TITLE
Document.json() Javadoc Clarification

### ISSUE THREAD

**Issue by Tyler-Yates** [stanfordnlp/CoreNLP#179]
The code example in the Javadoc for the `json` method in the `Document` class is not correct:
`String json = new Document("Lucy in the sky with diamonds").json(Document::parse, Document::ner);`

The `Document` class does not contain methods `parse` or `ner` so this code will not compile. It seems to me that `Sentence::parse` and `Sentence::nerTags` are the correct functions to put here.

Additionally, it seems that the functions supplied to the `json` method are only applied to the first sentence in the document:
`for (Function<Sentence, Object> f : functions) {
      f.apply(this.sentence(0));
    }`

Shouldn't the functions be applied to each sentence in the document since the method is supposed to return "the JSON string for this document"?

**Comment by gangeli** [comment]
I've updated the Javadoc to correctly use `Sentence::parse` etc. rather than `Document::parse`. The code itself is actually correct through: calling a function on a single sentence will actually annotate the entire document (that's how the pipeline is set up), so calling the same function on the other sentences in the document would have no effect.

**Comment by Tyler-Yates** [comment]
I commented in the commit but I'll say it here in the issue as well: The `Sentence` class does not have a method called `ner`, instead it should be `nerTags`.
