### ISSUE TITLE
Using languages other than English

### ISSUE THREAD

**Issue by leandermelms** [stanfordnlp/CoreNLP#210]
Hi, 

I've followed the [instructions](http://stanfordnlp.github.io/CoreNLP/cmdline.html#languages-other-than-english) using different languages than English, but still having trouble to set it up properly. 

I've:
- Edited the pom file
- Downloaded the extra model
- Executed `java -mx3g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP -props StanfordCoreNLP-german.properties -file german.txt -outputFormat text` at the root dir with the model file in place

I'm sure that I've missed something. It complains about not finding the german model file: Unable to open "StanfordCoreNLP-german.properties" as class path, filename or URL

Any help is greatly appreciated.

**Comment by J38** [comment]
Do you have the German models jar in the directory where you are running the command?  The '-cp "*"' is going to look in the directory the command is being run, and by default the German models jar is not in that directory.  If you edit the pom, you will have downloaded the German models jar into ~/.m2/repository, but if you then run that java command it's not going to look at your Maven stuff at all.  A simple fix for this is to just manually download the German models jar and put it in the distribution folder with everything else and this problem will go away.  WARNING: the neural net German parser was accidentally a French file, so that won't work right now.  Please let me know if you have any other issues.

**Comment by leandermelms** [comment]
Solved it. Thank you for your help!
