### ISSUE TITLE
Similar tool with liberal license?

### ISSUE THREAD

**Issue by nuuman** [stanfordnlp/CoreNLP#214]
I can't use this library because it's GPLv3. Does anyone know of a similar open source library with, uh, more liberal license terms?

**Comment by AngledLuffa** [comment]
Wow, you really know how to make friends.

**Comment by windweller** [comment]
I don't think @nuuman intends to insult students (I think the insult is towards the license). 

I'd suggest maybe BerkeleyNLP?
Also Scala has a series of NLP implementations in ScalaNLP (basically it's just BerkeleyNLP because David Hall developed it when he was at Berkeley). 

You can also find various independent implementations of various algorithms independently online.
