### ISSUE TITLE
Universal dependencies giving incorrect root

### ISSUE THREAD

**Issue by Rabrg** [stanfordnlp/CoreNLP#227]
The sentence 

> The American Football Conference (AFC) champion Denver Broncos defeated the National Football Conference (NFC) champion Carolina Panthers 24–10 to earn their third Super Bowl

 has the root being 'champion' when it should be 'defeated'

I'm using the latest maven release (3.6.0)

**Comment by Rabrg** [comment]
Another sentence where the root is incorrect:

> The American Football Conference (AFC) champion Denver Broncos defeated the National Football Conference (NFC) champion Carolina Panthers 24–10 to earn their third Super Bowl title.

I've encountered a lot more incorrect roots than just these two; they don't seem rare

**Comment by sebschu** [comment]
All our parsers are statistical parsers, which are trained on large treebanks. While they tend to work quite well on most sentences, they still only have an accuracy between 85-92%, so they still make mistakes. We can add this sentence to our training data, which might fix the problem the next time we release new models, but there will always be examples that the parser gets wrong.

**Comment by Rabrg** [comment]
@sebschu since the root dependency is objectively the most important dependency of a sentence couldn't checks be performed on it to make sure if it's even valid, and if not try the next highest probability word?

**Comment by sebschu** [comment]
If we were able to perform such a check, we could simply perform this check recursively and get 100% accurate dependency trees, so I doubt there is an easy way to achieve this ;) But if you have an idea on how to do that, let me know.

**Comment by Rabrg** [comment]
@sebschu doesn't the root need to be a verb, so its validity could simply be checked with POS tags?

**Comment by sebschu** [comment]
Not necessarily. For example, in a copular construction such as 

> John is a teacher.

_teacher_ is the root of the sentence. 

Further, many surface forms in English can be a verb or a noun and parsing errors are often a result of wrong POS tags. For instance, in your sentence, _champion_ is tagged as a verb and probably for this reason the parser makes _champion_ the root of the sentence.

**Comment by Rabrg** [comment]
Are you sure about that? I honestly don't know, but when I put the sentence into [Google's NLP API](https://cloud.google.com/natural-language/) (there is a demo if you scroll down a bit)  it says the root is 'is'

And when dropping my original sentence into the CoreNLP demo located [here](http://nlp.stanford.edu:8080/corenlp/process) it's detecting 'champion' to be a noun, but is still detecting it to be the root

**Comment by sebschu** [comment]
Yes, I'm 100% sure about that. (I'm part of the team who designed the Universal Dependencies representation.) Google uses a different dependency representation than we do.

And yeah, I ran it without the POS tagger (see [this SO post](http://stackoverflow.com/questions/27865825/how-to-get-dependency-parse-output-exactly-as-online-demo/27881956#27881956) for an explanation why this can lead to different results) and then _champion_ gets tagged as a verb. And if I use the NN-dependency parser at [corenlp.run](http://corenlp.run) it does identify the correct root. So the parse for this sentence really seems to depend on which parse you use.

I don't want to discourage you from implementing such a check and perhaps it will work well for your data, but parsing is a really hard task and rejecting a parse because the root is not a verb is going to produce incorrect parses for many sentences and phrases and therefore we won't put anything like that into CoreNLP.

**Comment by Rabrg** [comment]
Alright, thanks for the clarification
