### ISSUE TITLE
Duplicate nodes in dependecy graph

### ISSUE THREAD

**Issue by JonathanHuthmann** [stanfordnlp/CoreNLP#233]
Running this:
 ```java
 	public static void main(final String[] args) {
		Properties props = new Properties();
		props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref");
		StanfordCoreNLP pipeline = new StanfordCoreNLP(props);

		String text = "Which birds are protected under the National Parks and Wildlife Act?";

		Annotation document = new Annotation(text);

		pipeline.annotate(document);

		List<CoreMap> sentences = document.get(SentencesAnnotation.class);
		CoreMap sentence = sentences.get(0);

		SemanticGraph dependencies = sentence.get(CollapsedCCProcessedDependenciesAnnotation.class);

		System.out.println(dependencies.toString());
	}
````
creates output:

```
-> protected/VBN (root)
  -> birds/NNS (nsubjpass)
    -> Which/WDT (det)
  -> are/VBP (auxpass)
  -> Parks/NNP (nmod:under)
    -> under/IN (case)
    -> the/DT (det)
    -> National/NNP (compound)
    -> and/CC (cc)
    -> Act/NNP (conj:and)
      -> Wildlife/NNP (compound)
  -> Act/NNP (nmod:under)
  -> ?/. (punct)
  ```

So it duplicates the "Act" node. This is not right, is it?

**Comment by sebschu** [comment]
Yes, this example is not right but that is due to a parsing error. The parser returns the following parse of the noun phrase (NP) _National Parks and Wildlife Act_.

    (NP (DT the) (NNP National) (NNPS Parks)
            (CC and)
            (NNP Wildlife) (NNP Act)))))

According to this parse, _National Parks_ and _Wildlife Act_ are two conjoined noun phrases, but actually _National Parks and Wildlife_ should be a single NP that modifies _Act_.

Now the dependency graph doesn't actually contain two nodes for _Act_ but instead _Act_ depends both on _Wildlife_ and _protected_ and therefore it is printed twice if you use this output format. If the prepositional complement were a conjoined NP, then it would have made sense to add a relation between the verb and the second conjunct. For example, if the sentence were _The plane flies to Serbia and Slovenia._, then it would have made sense to make the implicit relation between _Slovenia_ and _flies_ explicit by adding an `nmod:to` relation between these two words. (See the discussion on p.3 of [this paper](http://nlp.stanford.edu/~sebschu/pubs/schuster-manning-lrec2016.pdf) for a more detailed explanation.) However, as the prepositional complement in your example is a single NP, there should not be an additional relation.

Unfortunately there isn't really anything that can be done about this. The dependency conversion code relies on a correct parse and when the parser makes a mistake, you often also end up with a wrong dependency tree.

**Comment by AngledLuffa** [comment]
FWIW it can sometimes be a benefit to add a sentence with the correct parse
to the training data.
