### ISSUE TITLE
CoreNLP tokenizer barfs on characters outside the basic multilingual plane

### ISSUE THREAD

**Issue by gcampax** [stanfordnlp/CoreNLP#248]
It seems CoreNLP does not deal with surrogates properly, at least in the English tokenizer.

Test case: tokenize 💩

Expected: 1 token
Actual:
Aug 17, 2016 8:34:58 PM edu.stanford.nlp.process.PTBLexer next
WARNING: Untokenizable: ? (U+D83D, decimal: 55357)
and the token disappears

**Comment by FedgeNo** [comment]
I'm just a guy who uses this stuff and although I don't really see this as a bug (this is language processing, not arbitrary binary data processing), I am going to make sure I am filtering whatever input I'm sending to it so this is a useful post for me. Thanks.

**Comment by gcampax** [comment]
It depends what you use CoreNLP for. In our case, we're using it as the first step in a semantic parser for a virtual assistant. We want to process arbitrary user input, and it is very annoying if the parser randomly drops a character without warning, especially a semantically rich one like an emoji.

**Comment by manning** [comment]
This fix has been a long time coming.... The problem was that up until today, we'd been using jflex 1.5.1 for European language tokenization and jflex 1.5.1 and below only supported the Unicode BMP. 

However, just today, I upgraded jflex to version 1.6.1 and then upgraded our tokenization code that builds on it to support emoji.

So, if you run using the code from HEAD, this should now work. Otherwise ... in version 3.8.0.
