### ISSUE TITLE
Compilation instructions

### ISSUE THREAD

**Issue by willmoy** [stanfordnlp/CoreNLP#249]
There are currently different compilation instructions in different places:
Website: http://nlp.stanford.edu/software/basic-compiling.txt (linked to from: http://stanfordnlp.github.io/CoreNLP/download.html)
Wiki: https://github.com/stanfordnlp/CoreNLP/wiki/Compilation-Instructions
README: https://github.com/stanfordnlp/CoreNLP/blob/master/README.md

Everything in basic-compiling.txt is in the wiki page. The README has slightly different instructions.

It might be helpful to consolidate all this in one place.

Some users (I'm one of them) aren't familiar with java, or things like maven, ant, etc. (e.g. https://github.com/stanfordnlp/CoreNLP/issues/138). So it's probably not helpful to have the platform-specific reference to brew install ant on the wiki page. I had no idea what brew was.

Finally, it might be worth explicitly saying (when?) you have to download the model jar at the bottom of the compilation instructions.

Thanks for sharing such powerful software.

**Comment by J38** [comment]
Thanks for bringing this up.  I will definitely spend time over the next month during the 3.7.0 release to make improvements to our documentation!

**Comment by burtonator** [comment]
Also, clarification on how you guys update maven central.  Rumor has it that there is a pom but I can't find it ...

**Comment by J38** [comment]
We're releasing 3.7.0 (beta) fairly soon.  That being said we probably won't release it to Maven before Thanksgiving.

The pom.xml is here:

https://github.com/stanfordnlp/CoreNLP/blob/master/doc/corenlp/pom-full.xml
________________________________

**Comment by J38** [comment]
Here is the pom.xml on Maven Central:


http://search.maven.org/#artifactdetails%7Cedu.stanford.nlp%7Cstanford-corenlp%7C3.6.0%7Cjar


Every time we do a release we submit the new version to Maven.

________________________________

**Comment by burtonator** [comment]
Thanks.  Yeah.  I saw the version on maven central so but couldn't figure out how the dependencies were built since I didn't see the pom.xml in the main repo.

Wouldn't it be better to put it in / and named pom.xml to go more along with convention?  

Would make it easier for us maven nerds to contribute.

**Comment by J38** [comment]
Sure I will look into moving it at some point soon!

________________________________

**Comment by J38** [comment]
I have changed it so on the main page there are some build instructions with Ant and Maven.

https://github.com/stanfordnlp/CoreNLP/blob/master/README.md

On the Download page the instructions are a bit different because those instructions are about altering the source code of the distribution and rebuilding it.  The instructions on our main GitHub page are about building the latest code if you get it from GitHub.

I also deleted the Wiki page to make things less confusing for people.
