### ISSUE TITLE
How to pass one's own word vectors ? Any example ?

### ISSUE THREAD

**Issue by shaktisd** [stanfordnlp/CoreNLP#296]
I can see in SentimentModel class there is a an api readWordVectors , I want to pass my own word vector to a new sentiment model ? How can I do it ? Is there an example file with the format , for the same ?
https://github.com/stanfordnlp/CoreNLP/blob/d558d95d80b36b5b45bc21882cbc0ef7452eda24/src/edu/stanford/nlp/sentiment/SentimentModel.java

**Comment by rstjobs** [comment]
java -cp "*" -mx5g edu.stanford.nlp.sentiment.BuildBinarizedDataset -input sample.txt
sample.text would contain training data, Example
 1 Today is not a good day. 
3 good
 3 good day
 3 a good day 
this will generate
(1 (1 Today) (1 (1 (1 (1 is) (1 not)) (3 (1 a) (3 (3 good) (1 day)))) (1 .)))
So you need to have hand written data for the new traning.

**Comment by loretoparisi** [comment]
Does the `readWordVectors` API support GloVe Word2vec format? Binary or text format?

**Comment by cheungtitus** [comment]
@rstjobs what is not clear is how do you break down each sentence into its phrases.

For example for this sentence.
`Today is not a good day.`

How do we know we should use the following.
```
good
good day
a good day
```

And not the following?
```
Today
not
is not a good day
```

**Comment by imranrajjad** [comment]
but how do you specifify the output file name? I ran the command on a tab separated file but did not get any output

**Comment by cheungtitus** [comment]
@imranrajjad I summarized all the steps for generating the default sentiment model file on https://github.com/stanfordnlp/CoreNLP/issues/742 and on the end of that post you can see a command on how to generate the model file.  That is not a problem.

The problem is how to generate the STree.txt file especially, and the list of questions I posted at the beginning of that question.
