### ISSUE TITLE
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Error deserializing / invalid stream header:

### ISSUE THREAD

**Issue by loretoparisi** [stanfordnlp/CoreNLP#322]
As soon as I complete the training, I'm saving the trained LinearClassifier resulting from method [makeClassifier](http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/classify/ColumnDataClassifier.html#makeClassifier-edu.stanford.nlp.classify.GeneralDataset-) using the static method [writeClassifier](http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/classify/LinearClassifier.html#writeClassifier-edu.stanford.nlp.classify.LinearClassifier-java.lang.String-)
When I try to load the saved model using the command line tool property `loadClassifier` I get an error:

```
ColumnDataClassifier invoked on Thu Dec 15 02:10:09 CET 2016 with arguments:
   -loadClassifier ./my_model
Loading classifier from ./my_model...
Exception in thread "main" edu.stanford.nlp.io.RuntimeIOException: Error deserializing ./my_model
	at edu.stanford.nlp.classify.ColumnDataClassifier.setProperties(ColumnDataClassifier.java:1580)
	at edu.stanford.nlp.classify.ColumnDataClassifier.<init>(ColumnDataClassifier.java:1926)
	at edu.stanford.nlp.classify.ColumnDataClassifier.main(ColumnDataClassifier.java:1946)
Caused by: java.io.StreamCorruptedException: invalid stream header: 303D4241
	at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:808)
	at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
	at edu.stanford.nlp.io.IOUtils.readStreamFromString(IOUtils.java:398)
	at edu.stanford.nlp.classify.ColumnDataClassifier.setProperties(ColumnDataClassifier.java:1574)
	... 2 more
```

While using the command line as usual - `serializeTo` and `loadClassifier` properties to save and load automatically, it works.

If I look at the source code I can see how a `LinearClassifier` will be load from the `loadClassifier` path [here](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/classify/ColumnDataClassifier.java#L1586) using an `IOUtils.readStreamFromString`, and the `IOUtils.writeStreamFromString` is used to serialize the classifier to the disk [here](https://github.com/stanfordnlp/CoreNLP/blob/master/src/edu/stanford/nlp/classify/ColumnDataClassifier.java#L2039), while the static method `writeClassifier` is using the `IOUtils.writeObjectToFile`, so apparently those two apis seem to do not have the same `BOM`:

```
Caused by: java.io.StreamCorruptedException: invalid stream header: 303D4241
```

**Comment by manning** [comment]
I think this isn't quite a bug, but what's provided in the API certainly isn't what you would like it to be....

The problem is that the serializeTo and loadClassifier methods in ColumnDataClassifier write to the file 2 objects – the classifier and then the Flags[] flags, which acts like a properties object in capture how the ColumnDataClassifier is extracting features from the input for feeding into the classifier – while writeClassifier from LinearClassifier is just writing the classifier, and so loadClassifier fails when it tries to read the Flags[]. And, unless you change the source code, flags is private, and so you can't read your own code. 

What does work is to not use loadClassifier, and instead to just use a ColumnDataClassifier, initialized with a Properties to produce features and then to load your classifier and to classify those features with it. That is illustrated working in [ClassifierDemo](https://github.com/stanfordnlp/CoreNLP/blob/d558d95d80b36b5b45bc21882cbc0ef7452eda24/src/edu/stanford/nlp/classify/demo/ClassifierDemo.java) – which currently doesn't use writeClassifier() but maybe more neatly could.

But it would clearly be nicer if you didn't have to do this and there were public methods in ColumnDataClassifier that did what serializeTo and loadClassifier do. I'll add them.

**Comment by loretoparisi** [comment]
@manning in fact I have realized the missing object after a bit then I have tried (I'm calling java from node in a Node.js backend context):

```javascript
// Linear Classifier instance
    // @see http://nlp.stanford.edu/nlp/javadoc/javanlp/edu/stanford/nlp/classify/LinearClassifier.html
    self.linearClassifier =  self.classifier.makeClassifierSync(self.dataSet);
    if(self.linearClassifier) {
        if( self.list.getPropertySync('printTo') ) { // print linear classifier as text
            self.linearClassifier.saveToFilename(self.list.getPropertySync('printTo')); // <--- this OK
        }
        if( self.list.getPropertySync('serializeTo') ) { // serialize linear classifier 

           // this serialization will cause the header error
            java.callStaticMethodSync("edu.stanford.nlp.classify.LinearClassifier", "writeClassifier", self.linearClassifier, self.list.getPropertySync('serializeTo'));
            

// this serialization will cause a EOF error
            var oos = java.callStaticMethodSync("edu.stanford.nlp.io.IOUtils", "writeStreamFromString", self.list.getPropertySync('serializeTo'));
            oos.writeObjectSync(self.linearClassifier);
            oos.closeSync();
        }
    }
```

So I have tried to add the properties, but did realize after that we have like in the classifier a `private` variable `this.flags=Flags[0]` so this will not work anyways:

```javascript
// this serialization will cause a cast exception
            var oos = java.callStaticMethodSync("edu.stanford.nlp.io.IOUtils", "writeStreamFromString", self.list.getPropertySync('serializeTo'));
            oos.writeObjectSync(self.linearClassifier);
             oos.writeObjectSync(self.list);
            oos.closeSync();
```

By the way I have updated to the latest `stanford-corenlp-3.6.0` while I was using before `3.5.x`.

**Comment by loretoparisi** [comment]
@gangeli 👍

**Comment by loretoparisi** [comment]
@manning thanks for the commit. Any idea of the release date?
