### ISSUE TITLE
Stanford nlp-Coreference resolution - “java.lang.OutOfMemoryError: Java heap space”

### ISSUE THREAD

**Issue by VRSupriya** [stanfordnlp/CoreNLP#365]
I tried to train the statistical coreference resolution system with conll 2012 trial data(http://conll.cemantix.org/2012/data.html). I wanted to train it for medical data. But I started with conll 2012 trial data inorder to understand the statistical coreference pipeline. I took only two ".conll" files of size less than 2MB(eng_0012.conll,eng_0014.conll). These two files contains total of 8 training docs.

I followed below link to build the model.
http://stanfordnlp.github.io/CoreNLP/coref.html
(java -Xmx60g -cp stanford-corenlp-3.7.0.jar:stanford-english-corenlp-models-3.7.0.jar:* edu.stanford.nlp.coref.statistical.StatisticalCorefTrainer -props )

Here the heap size is mentioned as 60g. I used 60g heap size and 15g swap memory and 16 core processor.

But I got "java.lang.OutOfMemoryError: Java heap space" exception while building the model.

Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
    at java.util.Arrays.copyOf(Arrays.java:3181)
    at java.util.ArrayList.grow(ArrayList.java:261)
    at java.util.ArrayList.ensureExplicitCapacity(ArrayList.java:235)
    at java.util.ArrayList.ensureCapacityInternal(ArrayList.java:227)
    at java.util.ArrayList.add(ArrayList.java:458)
    at      edu.stanford.nlp.coref.statistical.Clusterer.getFeatures(Clusterer.java:661)
    at edu.stanford.nlp.coref.statistical.Clusterer.access$700(Clusterer.java:27)
    at edu.stanford.nlp.coref.statistical.Clusterer$State.getActions(Clusterer.java:460)
    at edu.stanford.nlp.coref.statistical.Clusterer.runPolicy(Clusterer.java:225)
    at edu.stanford.nlp.coref.statistical.Clusterer.doTraining(Clusterer.java:167)
    at edu.stanford.nlp.coref.statistical.StatisticalCorefTrainer.doTraining(StatisticalCorefTrainer.java:127)
    at edu.stanford.nlp.coref.statistical.StatisticalCorefTrainer.main(StatisticalCorefTrainer.java:146)
When i reduced the training doc for from 8 to 4 in "doTraining" method of "edu/stanford/nlp/coref/statistical/Clusterer.java" class, it ran successfully.

for (ClustererDoc trainDoc : trainDocs){
    examples.add(runPolicy(trainDoc, Math.pow(EXPERT_DECAY(iteration +1))));
}
I don't understand why I am getting this out of memory exception even after giving required configuration for a very small amount of data(less than 2 MB)

Is there any way to optimize the memory usage?

When I went through the source code I found some files like demonyms.txt, gender.data.gz, inanimate.unigrams.txt, state-abbrevations.txt etc. Do I need to create any files specifying medical entities for training the medical domain to get better accuracy ?

**Comment by kno10** [comment]
`Pair<Integer, Integer>` is very memory inefficient. 16 to 32 bytes for the `Pair`, plus 16 to 24 bytes for each `Integer` (if they aren't <127). So in the worst case, `Pair<Integer, Integer>` will require 80 bytes for 8 bytes of actual data.

Beware that using a heap size larger than 32g disables [compressed pointers](https://wiki.openjdk.java.net/display/HotSpot/CompressedOops). So up to 32g, your `Pair<Integer,Integer>` occupies 16, 32 or 48 bytes (depending on the int values). Over 32g, this increases to 32, 56 or 80 bytes, so memory consumption almost doubles for these tiny objects.

Changing the code to use an `IntIntPair` (like [this](https://github.com/elki-project/elki/blob/950c9b8e9f2eb06e7abfc6e4518b65e35583d235/elki-core-util/src/main/java/de/lmu/ifi/dbs/elki/utilities/pairs/IntIntPair.java)) will reduce this to 16 to 24 bytes for the whole pair (yes, you can store an `IntIntPair` for the cost of storing an `Integer`, because object sizes are rounded to 8 bytes).

Because this has one level less of memory indirection (the `int`s are stored in the pair, not in a boxed `Integer`), the performance will also be much better (plus, you reduce garbage collection).

Because you are running out of memory, you may want to consider to implement and contribute this improvement. But from a quick look at the code, there are many other uses of memory-wasting data structures in this class, unfortunately. Without a heap dump, it's hard to predict if above change is enough, or whether you need to do more memory optimization. But based on your stack trace, there may be many `Pair<Integer, Integer>` here, because you run out of memory when resizing `ArrayList<Pair<Integer, Integer>>`).
