### ISSUE TITLE
java.io.IOException: The process cannot access the file because another process has locked a portion of the file

### ISSUE THREAD

**Issue by coolfeature** [stanfordnlp/CoreNLP#399]
There are many Maven tests failing with:

java.io.IOException: The process cannot access the file because another process has locked a portion of the file

eg

  testPutLocal(edu.stanford.nlp.util.FileBackedCacheTest)

**Comment by J38** [comment]
When I build the project with `mvn package` I am not getting any test failures.  Could you describe when you are seeing this error?

**Comment by MartinLidh** [comment]
On windows i get this exact problem when i use mvn package.

Tests in error:
  testPutLocal(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException:                                                       The process cannot access the file because another process has locked a portion                                                       of the file
  testCacheWritingToDisk(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOE                                                      xception: The process cannot access the file because another process has locked                                                       a portion of the file
  testCollision(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException:                                                       The process cannot access the file because another process has locked a portion                                                       of the file
  testGetLocal(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException:                                                       The process cannot access the file because another process has locked a portion                                                       of the file
  testMerge(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The                                                       process cannot access the file because another process has locked a portion of                                                       the file
  testSize(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: The                                                       process cannot access the file because another process has locked a portion of t                                                      he file
  testContainsFile(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOExcepti                                                      on: The process cannot access the file because another process has locked a port                                                      ion of the file
  testPutFile(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: T                                                      he process cannot access the file because another process has locked a portion o                                                      f the file
  testGetFile(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException: T                                                      he process cannot access the file because another process has locked a portion o                                                      f the file
  testContainsLocal(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOExcept                                                      ion: The process cannot access the file because another process has locked a por                                                      tion of the file
  testMapValueGoodPattern(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IO                                                      Exception: The process cannot access the file because another process has locked                                                       a portion of the file
  testContainsRemoveFromMemory(edu.stanford.nlp.util.FileBackedCacheTest): java.                                                      io.IOException: The process cannot access the file because another process has l                                                      ocked a portion of the file
  testIterator(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOException:                                                       The process cannot access the file because another process has locked a portion                                                       of the file
  testComprehension(edu.stanford.nlp.util.FileBackedCacheTest): java.io.IOExcept                                                      ion: The process cannot access the file because another process has locked a por                                                      tion of the file

Tests run: 1196, Failures: 16, Errors: 14, Skipped: 1

**Comment by ozdenakca** [comment]
I get the same problems as Martin.

**Comment by Shirlene-lim** [comment]
Me too. Any solution so far?

**Comment by 121eddie** [comment]
same. Why was this issue closed?

**Comment by AngledLuffa** [comment]
This is an issue on Windows, not on Linux.  As far as I can tell there is something screwed up with the locking mechanism on Windows.  For example, here is a small program which works fine on Linux and dies horribly on Windows.

With this in mind, I'm going to file a bug with Java and say "not our fault" until told otherwise.

```
import java.io.*;
import java.nio.channels.*;

public class foo {
  public static void main(String[] args) throws IOException {
    RandomAccessFile fout = new RandomAccessFile( "foo", "rw" );
    FileChannel channel = fout.getChannel();

    // this doesn't work
    FileLock lock = channel.lock(1, 10, true);

    // this works
    //FileLock lock = channel.lock();

    // Write the new value to the file
    byte[] bytes = "Hello World\n".getBytes();
    fout.write( bytes );
    fout.close();
  }
}
```
