### ISSUE TITLE
Japanese model

### ISSUE THREAD

**Issue by vochicong** [stanfordnlp/CoreNLP#450]
Hi, I am interested to using CoreNLP (and DeepDive) with Japanese.
Are you working on Japanese?
And how can I start building a Japanese model?
How did you build Chinese or English models?

Thanks!

**Comment by manning** [comment]
No, we are not currently working on Japanese. The first requirement to make models for any language is labeled data to train models from. Most of the components in CoreNLP use supervised learning. Traditionally, the public availability of Japanese language corpora hasn't been very good, but, now, e.g., the Japanese Universal Dependencies corpora could be used to train several components (segmenter, POS, depparse). However, I still don't know of any usable Japanese NER data. The other requirement is somebody willing to do the work. In general, our expansions to other languages have occurred because somebody was interested in having the language available for some reason.

**Comment by vochicong** [comment]
@manning Thank you for your reply. Actually, I am an NLP newbie and still don't fully understand your valuable answer ;) 
But I think that [Kuromoji](https://github.com/atilika/kuromoji), a Japanese morphological analyzer implemented in Java, looks promising to be embedded in CoreNLP.

I will search for Japanese NER data and if I find one I will share it with you.

BTW, I enjoy your [Natural Language Processing with Deep Learning course](https://www.youtube.com/watch?v=OQQ-W_63UgQ) very much! Thanks for it too!

**Comment by vochicong** [comment]
I found [jigg](https://github.com/mynlp/jigg). It's said having similar interface to CoreNLP, including CoreNLP and [Kuromoji](https://github.com/atilika/kuromoji) a Japanese tokenizer. The authors are inspired by CoreNLP, once tried to make an Japanese extension to CoreNLP, but later decided to make jigg for more flexibility.

For Japanese NER, they use [JUMAN/KNP](https://github.com/mynlp/jigg/blob/3dfe52abfbb87caba1ecbdc594058e58ca1a0db3/src/main/scala/jigg/pipeline/KNPAnnotator.scala).

**Comment by AngledLuffa** [comment]
FWIW (mostly for archival reasons at this point) there are now Japanese models for stanfordnlp

https://stanfordnlp.github.io/stanfordnlp/models.html#human-languages-supported-by-stanfordnlp

**Comment by vochicong** [comment]
Thank you @AngledLuffa for your update.

**Comment by devanghingu** [comment]
@AngledLuffa @vochicong i just checked standford package and stanza. but still not support for process relation extraction(`kbp`)

**Comment by AngledLuffa** [comment]
There is no relation extraction model in Stanza
