### ISSUE TITLE
CoreNLP 3.8.0 questions

### ISSUE THREAD

**Issue by dandelionred** [stanfordnlp/CoreNLP#464]
README says:

```
---------------------------------
CHANGES
---------------------------------

2017-06-09    3.8.0     Web service annotator, discussion forum 
                        handling, new French and Spanish models 
```

1. What are those "Web service annotator" and "discussion forum handling"?

2. Are there any significant changes/improvements to NER (or corresponding models for the NER pipeline) compared to 3.7.0?

**Comment by manning** [comment]
1. a. See the class edu.stanford.nlp.pipeline.GenericWebServiceAnnotator. This is the ability to put an annotator in an annotation pipeline that is calling an external webservice. b. Discussion forum handling refers to the new options in CleanXml document here: https://stanfordnlp.github.io/CoreNLP/cleanxml.html#example-handling-discussion-forums . It's fairly specialized, but might have various uses in document processing.

2. No, but we've done quite a bit of work on improving NER since then, so there will be in the next version.
