### ISSUE TITLE
online training for NER?

### ISSUE THREAD

**Issue by rpedela** [stanfordnlp/CoreNLP#488]
I am curious if online training is possible to implement especially for NER? Is it a matter of writing the code to load models or are there algorithmic or structural reasons for the limitation?

**Comment by J38** [comment]
I'm not sure what would happen if you tried to load pre-learned weights and then continued to train on new data.  Currently the code isn't set up to support that to the best of my knowledge.  If over time you have a new collection of sentences since your original training data, I would just recommend building a new model with the entire training data set.
