### ISSUE TITLE
Issue in tokenization

### ISSUE THREAD

**Issue by jplu** [stanfordnlp/CoreNLP#503]
Hello,

I have noticed few bugs when tokenizing tweets with CoreNLP 3.8.0 released version. I'm providing several examples.

Example 1:

```
Happy #StarWars week! Ever wonder what was going on with Uncle Owen's dad? Check out .@WHMPodcast's rant on Ep2 https://t.co/9iJMMkAokT
```

The tokenization of this tweet I get is the following:

```
[Text=Happy CharacterOffsetBegin=0 CharacterOffsetEnd=5]
[Text=#StarWars CharacterOffsetBegin=6 CharacterOffsetEnd=15]
[Text=week CharacterOffsetBegin=16 CharacterOffsetEnd=20]
[Text=! CharacterOffsetBegin=20 CharacterOffsetEnd=21]
[Text=Ever CharacterOffsetBegin=22 CharacterOffsetEnd=26]
[Text=wonder CharacterOffsetBegin=27 CharacterOffsetEnd=33]
[Text=what CharacterOffsetBegin=34 CharacterOffsetEnd=38]
[Text=was CharacterOffsetBegin=39 CharacterOffsetEnd=42]
[Text=going CharacterOffsetBegin=43 CharacterOffsetEnd=48]
[Text=on CharacterOffsetBegin=49 CharacterOffsetEnd=51]
[Text=with CharacterOffsetBegin=52 CharacterOffsetEnd=56]
[Text=Uncle CharacterOffsetBegin=57 CharacterOffsetEnd=62]
[Text=Owen CharacterOffsetBegin=63 CharacterOffsetEnd=67]
[Text='s CharacterOffsetBegin=67 CharacterOffsetEnd=69]
[Text=dad CharacterOffsetBegin=70 CharacterOffsetEnd=73]
[Text=? CharacterOffsetBegin=73 CharacterOffsetEnd=74]
[Text=Check CharacterOffsetBegin=75 CharacterOffsetEnd=80]
[Text=out CharacterOffsetBegin=81 CharacterOffsetEnd=84]
[Text=.@WHMPodcast CharacterOffsetBegin=85 CharacterOffsetEnd=97]
[Text='s CharacterOffsetBegin=97 CharacterOffsetEnd=99]
[Text=rant CharacterOffsetBegin=100 CharacterOffsetEnd=104]
[Text=on CharacterOffsetBegin=105 CharacterOffsetEnd=107]
[Text=Ep2 CharacterOffsetBegin=108 CharacterOffsetEnd=111]
[Text=https://t.co/9iJMMkAokT CharacterOffsetBegin=112 CharacterOffsetEnd=135]
```

As one can see, there is a problem with the token number 19: ```.@WHMPodcast``` it should be split into two tokens ```.``` and ```@WHMPodcast```.

Example 2:

```
Believe me, I #boycott disgusting corporate #media #ABCNews #Trump trash and their advertisers. .@mmfa -- @BernieSanders, you rock!
```

Same case than the example 1 with ```.@mmfa```

Example 3:

```
RT @JoshEstrin: #PHOTOS -  #StarWars: #TheForceAwakens is it all hype? https://t.co/kFp9mnMv8l via .@JoshEstrin
```

Same case than the example 1 with ```.@JoshEstrin```

Example 4:

```
📷 .@MatthewDaddario at #StarWars #TheForceAwakens premiere Part 1 #Shadowhunters Photo : Getty Images https://t.co/LVLghZyOnr
```

Same case than the example 1 with ```.@MatthewDaddario```

Example 5:

```
.@StarWarsAUNZ I have chosen the #Darkside & have my tix for #StarWars #TheForceAwakens on Dec 17! https://t.co/I9Inmd4iuV
```

Same case than the example 1 with ```.@StarWarsAUNZ```

Example 6:

```
RT @Suns: What happens when you combine @50cent, #StarWars and introductions at an @NBA game? This.
```

The tokenization of this tweet I get is the following:

```
[Text=RT CharacterOffsetBegin=0 CharacterOffsetEnd=2]
[Text=@Suns CharacterOffsetBegin=3 CharacterOffsetEnd=8]
[Text=: CharacterOffsetBegin=8 CharacterOffsetEnd=9]
[Text=What CharacterOffsetBegin=10 CharacterOffsetEnd=14]
[Text=happens CharacterOffsetBegin=15 CharacterOffsetEnd=22]
[Text=when CharacterOffsetBegin=23 CharacterOffsetEnd=27]
[Text=you CharacterOffsetBegin=28 CharacterOffsetEnd=31]
[Text=combine CharacterOffsetBegin=32 CharacterOffsetEnd=39]
[Text=@ CharacterOffsetBegin=40 CharacterOffsetEnd=41]
[Text=50cent CharacterOffsetBegin=41 CharacterOffsetEnd=47]
[Text=, CharacterOffsetBegin=47 CharacterOffsetEnd=48]
[Text=#StarWars CharacterOffsetBegin=49 CharacterOffsetEnd=58]
[Text=and CharacterOffsetBegin=59 CharacterOffsetEnd=62]
[Text=introductions CharacterOffsetBegin=63 CharacterOffsetEnd=76]
[Text=at CharacterOffsetBegin=77 CharacterOffsetEnd=79]
[Text=an CharacterOffsetBegin=80 CharacterOffsetEnd=82]
[Text=@NBA CharacterOffsetBegin=83 CharacterOffsetEnd=87]
[Text=game CharacterOffsetBegin=88 CharacterOffsetEnd=92]
[Text=? CharacterOffsetBegin=92 CharacterOffsetEnd=93]
[Text=This CharacterOffsetBegin=94 CharacterOffsetEnd=98]
[Text=. CharacterOffsetBegin=98 CharacterOffsetEnd=99]
```

As one can see there is a problem for the user mention ```@50cent``` that has been split into two tokens instead of keeping it as it is.

Example 7:

```
RT @BiIlionaires: #TheForceAwakens inspired vehicles are a big hit in LA.
```

The tokenization of this tweet I get is the following:

```
[Text=RT CharacterOffsetBegin=0 CharacterOffsetEnd=2]
[Text=@BiIlionaires CharacterOffsetBegin=3 CharacterOffsetEnd=16]
[Text=: CharacterOffsetBegin=16 CharacterOffsetEnd=17]
[Text=#TheForceAwakens CharacterOffsetBegin=18 CharacterOffsetEnd=34]
[Text=inspired CharacterOffsetBegin=35 CharacterOffsetEnd=43]
[Text=vehicles CharacterOffsetBegin=44 CharacterOffsetEnd=52]
[Text=are CharacterOffsetBegin=53 CharacterOffsetEnd=56]
[Text=a CharacterOffsetBegin=57 CharacterOffsetEnd=58]
[Text=big CharacterOffsetBegin=59 CharacterOffsetEnd=62]
[Text=hit CharacterOffsetBegin=63 CharacterOffsetEnd=66]
[Text=in CharacterOffsetBegin=67 CharacterOffsetEnd=69]
[Text=LA. CharacterOffsetBegin=70 CharacterOffsetEnd=72]
[Text=. CharacterOffsetBegin=72 CharacterOffsetEnd=73]
```

As one can see, there is a problem with the last token the ```.``` is still attached to the token ```LA``` whereas the offset has been properly computed.

**Comment by jplu** [comment]
Another example:

```
“@people: A woman built the perfect #StarWars costume for her dog https://t.co/VJRQwNZB0t https://t.co/nmNROB7diR”@guacomole123
```

The tokenization of this tweet I get is the following:

```
[Text=`` CharacterOffsetBegin=0 CharacterOffsetEnd=1]
[Text=@people CharacterOffsetBegin=1 CharacterOffsetEnd=8]
[Text=: CharacterOffsetBegin=8 CharacterOffsetEnd=9]
[Text=A CharacterOffsetBegin=10 CharacterOffsetEnd=11]
[Text=woman CharacterOffsetBegin=12 CharacterOffsetEnd=17]
[Text=built CharacterOffsetBegin=18 CharacterOffsetEnd=23]
[Text=the CharacterOffsetBegin=24 CharacterOffsetEnd=27]
[Text=perfect CharacterOffsetBegin=28 CharacterOffsetEnd=35]
[Text=#StarWars CharacterOffsetBegin=36 CharacterOffsetEnd=45]
[Text=costume CharacterOffsetBegin=46 CharacterOffsetEnd=53]
[Text=for CharacterOffsetBegin=54 CharacterOffsetEnd=57]
[Text=her CharacterOffsetBegin=58 CharacterOffsetEnd=61]
[Text=dog CharacterOffsetBegin=62 CharacterOffsetEnd=65]
[Text=https://t.co/VJRQwNZB0t CharacterOffsetBegin=66 CharacterOffsetEnd=89]
[Text=https://t.co/nmNROB7diR”@guacomole123 CharacterOffsetBegin=90 CharacterOffsetEnd=127
```

As one can see, the last token should be split into three different tokens ```https://t.co/nmNROB7diR```, ```”``` and ```@guacomole123```

**Comment by jplu** [comment]
Another example:

```
RT @ShirleyHoman481: '#StarWars' Premiere Street Closures Are “Bigger Than the Oscars": Four blocks of Hollywood Blvd. -- from Highland… ht…
```

The tokenization of this tweet I get is the following:

```
[Text=RT CharacterOffsetBegin=0 CharacterOffsetEnd=2]
[Text=@ShirleyHoman481 CharacterOffsetBegin=3 CharacterOffsetEnd=19]
[Text=: CharacterOffsetBegin=19 CharacterOffsetEnd=20]
[Text=' CharacterOffsetBegin=21 CharacterOffsetEnd=22]
[Text=#StarWars CharacterOffsetBegin=22 CharacterOffsetEnd=31]
[Text=' CharacterOffsetBegin=31 CharacterOffsetEnd=32]
[Text=Premiere CharacterOffsetBegin=33 CharacterOffsetEnd=41]
[Text=Street CharacterOffsetBegin=42 CharacterOffsetEnd=48]
[Text=Closures CharacterOffsetBegin=49 CharacterOffsetEnd=57]
[Text=Are CharacterOffsetBegin=58 CharacterOffsetEnd=61]
[Text=`` CharacterOffsetBegin=62 CharacterOffsetEnd=63]
[Text=Bigger CharacterOffsetBegin=63 CharacterOffsetEnd=69]
[Text=Than CharacterOffsetBegin=70 CharacterOffsetEnd=74]
[Text=the CharacterOffsetBegin=75 CharacterOffsetEnd=78]
[Text=Oscars CharacterOffsetBegin=79 CharacterOffsetEnd=85]
[Text='' CharacterOffsetBegin=85 CharacterOffsetEnd=86]
[Text=: CharacterOffsetBegin=86 CharacterOffsetEnd=87]
[Text=Four CharacterOffsetBegin=88 CharacterOffsetEnd=92]
[Text=blocks CharacterOffsetBegin=93 CharacterOffsetEnd=99]
[Text=of CharacterOffsetBegin=100 CharacterOffsetEnd=102]
[Text=Hollywood CharacterOffsetBegin=103 CharacterOffsetEnd=112]
[Text=Blvd. CharacterOffsetBegin=113 CharacterOffsetEnd=118]
[Text=-- CharacterOffsetBegin=119 CharacterOffsetEnd=121]
[Text=from CharacterOffsetBegin=122 CharacterOffsetEnd=126]
[Text=Highland CharacterOffsetBegin=127 CharacterOffsetEnd=135]
[Text=... CharacterOffsetBegin=135 CharacterOffsetEnd=136]
[Text=ht CharacterOffsetBegin=137 CharacterOffsetEnd=139]
[Text=... CharacterOffsetBegin=139 CharacterOffsetEnd=140]
```

As one can see, the token ```Blvd.``` should be split into two different tokens ```Blvd``` and ```.```

**Comment by jplu** [comment]
Hello,

I also noticed another tokenization issue that is not about tweets but about a sentence from a Wikipedia page.

```
In 2009, Wiesel criticized the Vatican for lifting the excommunication of controversial bishop Richard Williamson, a member of the Society of Saint Pius X.
```

The last token is ```X.``` instead of ```X``` and ```.```

**Comment by manning** [comment]
Hi Julien, thanks a lot for the examples. We have worked hard to make the Stanford tokenizer high quality – and, indeed, I think in practice it almost always wins when people evaluate various tokenizers on a text type for which one tokenizer was not specifically adapted, but nevertheless, there are necessarily limits to what a deterministic, finite automaton tokenizer, even a complex one can do correctly…. Some day we may just substitute in a neural network segmenter, but it would be at a very different point on the speed/quality spectrum. I looked through all your examples, and I think this is what can and can't be done:

Examples 1-5: These are all the same phenomenon, where the "." is kept with a twitter user name. It's difficult to know how to treat this. You could regard the "." as an escape character, as a backslash is often used, and so it appropriately says with the token. At any rate, since much of our and application code regards a period by itself as a sentence ending, it would definitely be deleterious to make the "." its own token. So, for the moment, I think the best choice is just to leave it as is, and you'll have to remove such dots to get twitter user names as needed….

Example 6: This was also deliberate, if here wrong. While the true regex for a twitter name is /@[A-Za-z0-9_]{1,15}, we had deliberately excluded ones that start with numbers, since they are (relatively) uncommon (though they do exist) and there are lots of other places in informal writing where "@" is followed by numbers, not always with spaces, such as: "@60fps", "@145bpm", "@5am". But 50 Cent is a prominent guy! For the moment I have special cased just this string so it is now treated as a twitter name. So, fixed.

Example 7: Fixed. (This was buggy because there is also an abbreviation "La." for "Louisiana", but it is now restricted to lowercase "a" examples.)

Example 8: Fixed. Curly quotes didn't terminate a URL before.

Example 9: Not sure I agree. For abbreviations like "Blvd." we standardly keep the period with the abbreviation. It's not so clear from context that this is a sentence end. Not changed.

Example 10: The tokenization here is clearly wrong, but in most circumstances single letters followed by periods are abbreviations, such as in names like "Angel X. Chang". It wasn't so clear how to fix this case while preserving the general behavior, so this remains unfixed.

So, the fixed ones are now fixed in github HEAD, and you could cherrypick the latest files, or wait for the next release.

**Comment by jplu** [comment]
Thank you very much @manning for the fixes and the explanation. Crystal clear.
