### ISSUE TITLE
Inconsistency of NER tagging with 3.6 and 3.8

### ISSUE THREAD

**Issue by DarkDataAnalytics** [stanfordnlp/CoreNLP#516]
I asked the question on stackoverflow and also here. 

I am really puzzled by the results I get from CoreNLP (I am still using 3.6, currently upgrading to 3.8, and I used the online tool on the website to test with 3.8).

Look for example at the sentences below:

1) The Audit Committee has selected PricewaterhouseCoopers, which has audited our financial statements annually since 2004, to serve as our independent registered public accounting firm for Fiscal 2018.
2) Our lead audit partner at PricewaterhouseCoopers serves no more than five consecutive years in that role.
In (2), PricewaterhouseCoopers is tagged as as "ORGANIZATION" (which is what I want), HOWEVER it is NOT tagged as such in (1). **What am I missing here?**

Now if I add to the mix:

3) If our stockholders do not ratify the selection, the AC will reconsider whether or not to retain PricewaterhouseCoopers.
4) The AC believes it is in the best interests of NVIDIA and our stockholders to retain 
PricewaterhouseCoopers.

PricewaterhouseCoopers is not tagged correctly in either (3) or (4). In (4) NVIDIA is tagged correctly though. Why is that?

**Comment by manning** [comment]
You're not missing anything. It's disappointing that things don't work better here, but that's how it is. While NER systems attempt to guess the right analysis from context, and it works in 2., in truth they remain considerably reliant on words that they have seen in training data, and in this case, our model hadn't seen "PricewaterhouseCoopers" in training data, and it doesn't look very classically like a company name -- or anything else, for that matter.

This will be fixed in the next version, but most likely just by the crude solution of data augmentation.

**Comment by DarkDataAnalytics** [comment]
Thanks a lot for your answer.
