### ISSUE TITLE
While loading the MaxentTagger , getting Cast exception

### ISSUE THREAD

**Issue by lokeshkumarn** [stanfordnlp/CoreNLP#573]
Loading default properties from tagger stanfordmodels/english-left3words-distsim.tagger
Reading POS tagger model from stanfordmodels/english-left3words-distsim.tagger ... Exception in thread "main" java.lang.ClassCastException: edu.stanford.nlp.process.AmericanizeFunction cannot be cast to edu.stanford.nlp.util.Function

MaxentTagger tagger = new MaxentTagger(taggerPath);

**Comment by manning** [comment]
This doesn't reproduce for me on a clean installation of CoreNLP v3.8.

```
$ cd ~/Software/stanford-corenlp-full-2017-06-09
$ java -cp "*" edu.stanford.nlp.tagger.maxent.MaxentTagger -model edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger -textFile input.txt
[main] INFO edu.stanford.nlp.tagger.maxent.TaggerConfig - Loading default properties from tagger edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Loading POS tagger from edu/stanford/nlp/models/pos-tagger/english-left3words/english-left3words-distsim.tagger ... done [1.3 sec].
Stanford_NNP University_NNP is_VBZ located_JJ in_IN California_NNP ._.
It_PRP is_VBZ a_DT great_JJ university_NN ,_, founded_VBN in_IN 1891_CD ._.
[main] INFO edu.stanford.nlp.tagger.maxent.MaxentTagger - Tagged 17 words at 99.42 words per second.
```

I think the problem here is that you have more than one version of (parts of) Stanford CoreNLP or CoreNLP models on your classpath. That or you're using an old version of CoreNLP. Through v3.4.1, we had an interface edu.stanford.nlp.util.Function which edu.stanford.nlp.process.AmericanizeFunction implemented, but as part of the upgraded to Java 8, we stopped using our own Function class and changed everything over to java.util.function.Function. It looks like your somehow loading classes that have v3.4.1 or older and some (old class) code is trying to cast a (newer class) AmericanizeFunction which is a java.util.function.Function to the old interface edu.stanford.nlp.util.Function.

I'd look carefully through what's in your classpath.  Perhaps look at this discussion: https://nlp.stanford.edu/software/pos-tagger-faq.html#nosuchmethoderror
