### ISSUE TITLE
why I get this Error: Could not find or load main class edu.stanford.nlp.pipeline.StanfordCoreNLP

### ISSUE THREAD

**Issue by leolle** [stanfordnlp/CoreNLP#618]
I unzip the downloaded 3.8 core nlp full version from https://stanfordnlp.github.io/CoreNLP/download.html, and do the exact steps as Steps to setup from the official release.
I am running an Ubuntu 14.04, java 1.8.
The error pops up when running:
`java -mx3g edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat json -file input.txt`

**Comment by MissOgra** [comment]
I'm having the same issue! I'm executing it from the directory stanford-corenlp-full-2018-01-31... MacOS Sierra, java 1.8

**Comment by MissOgra** [comment]
I could make it work like this:

`java -cp "*" -Xmx2g edu.stanford.nlp.pipeline.StanfordCoreNLP -annotators tokenize,ssplit,pos,lemma,ner,parse,dcoref -file input.txt`

**Comment by J38** [comment]
Yes you definitely need to add the `-cp "*"` to your command to make sure all of the jars in the distribution folder are accessed.

**Comment by krutikabapat** [comment]
I was also facing the same issue. The below command solved the issue.
``` export CLASSPATH=\$CLASSPATH:$/PATH/TO/DIRECTORY/CORENLP/*  ```

**Comment by shawaiz3138** [comment]
i was also facing same issue.

**Comment by AyeshaSarwar** [comment]
I am facing the same issue However, I have added the path in my environment variables as CLASSPATH.
I am using Windows 10.
![Capture](https://user-images.githubusercontent.com/51691311/81843740-77111600-9567-11ea-83a2-db74fcdf79ac.PNG)

**Comment by AngledLuffa** [comment]
What command line are you using?  It is unable to load the class?

I'm not sure the *.jar is needed.  You can try it with just *

Why do people attach images of text?

**Comment by AyeshaSarwar** [comment]
I was adding it as a separate variable in my environment variables. Fixed it when added it to path using set path from my cmd.
Thanks

**Comment by shawaiz3138** [comment]
hy, basically i am working on preprocessing using CoreNLP in java, one
error come,
Unrecognized option: -annotators
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
have any idea?

**Comment by AngledLuffa** [comment]
I have an idea: you could tell us the command line you used

**Comment by shawaiz3138** [comment]
yes

**Comment by AngledLuffa** [comment]
Look, I can see you're relatively new here, so let me explain a couple things:

- We're not psychic.  If you don't tell us how you are getting the wrong result, we can't tell you how to get the right result
- This is a new issue.  Please open a new issue rather than piggybacking off a different issue.  Look for the big green button to the right of the search bar.

Having said that, my best guess is you did something like

`java -annotators "tokenize,ssplit,..."`

and forgot to include the main class `edu.stanford.nlp.pipeline.StanfordCoreNLP`.  Alternatively, you might have put the arguments before the main class rather than after.  

`-cp "*"`   is a java argument
`-annotators "tokenize,ssplit,..."` is an argument for the main class

The command line goes

`java [java_args] main_class [main_class_args]`

**Comment by AyeshaSarwar** [comment]
> What command line are you using? It is unable to load the class?
> 
> I'm not sure the *.jar is needed. You can try it with just *
> 
> Why do people attach images of text?

I was adding the jar files in CLASSPATH variable. I added in the PATH variable in system env variables and it worked.

**Comment by shawaiz3138** [comment]
First of all thanks, for reply
i use this command that's sow in attached picture..
please provide its solution because it's my project

**Comment by AngledLuffa** [comment]
Thanks for making me smile on week 8 of quarantine :)
