### ISSUE TITLE
Tokenizer increases the number of lines in a file

### ISSUE THREAD

**Issue by Tina-19** [stanfordnlp/CoreNLP#619]
I have a text file that contains, let's say, 20,000 lines. When I use the following command the number of lines increases to like 20,100 and that's not what I want. I want to keep the number of lines to the same 20,000.
`java edu.stanford.nlp.process.PTBTokenizer -preserveLines -lowerCase input.txt`

What goes wrong?

**Comment by manning** [comment]
I share your pain. Honestly.

In cases like this, it'd be really useful to include a pointer to an example input file that doesn't work, so people can check what is causing your problem. However, I suspect it is the following:

Unicode includes "line separator" and "paragraph separator" characters and Unicode says that you accept them. See e.g., http://unicode.org/standard/reports/tr13/tr13-5.html

However, Unix, Linux utilities, etc. don't recognize them and count only the traditional \n|\r|\r\n. And PTBTokenizer does normalize line separation. Hence, if your input text contains, say U+2028 Line Separator characters, the Unix wc utility will report more lines after tokenization than before, even though line breaks have been preserved, according to Unicode.

Try this: download the Perl uniwc script from https://raw.githubusercontent.com/briandfoy/Unicode-Tussle/master/script/uniwc

Run it on `input.txt` and `input.tok` and see if it reports the same number of lines for each file. If it does, the above is your problem, and in a certain Unicode sense, our tokenizer did indeed preserve the line count.  

If not, please send a pointer to an example file where this doesn't work.

Note: I do realize that this is annoying and can see how it would be useful to have an option that always preserved lines in the traditional unix sense. It doesn't presently exist though, and wouldn't be trivial to add, since the rest of the code assumes normalization around an abstract notion of a "new line".
