### ISSUE TITLE
Dependency: "Dep" tag

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#620]
This is a feature request, not a bug. 
=-=-=-

The "dep" tag indicates that the parser was unable to determine a likely tag. Conceptually, it makes sense to have a label indicating "I don't know", however, practically it doesn't help. My request is to either:
1. Never return a Dep tag (always return a best guess)
2. Return the Dep tag, along with a best guess: (DEP:TAG-X)

**Comment by AngledLuffa** [comment]
The statistical model already does this, but with the `dep` in the first place.  If the constituency parser output is converted to dependencies, the conversion is done via a sequence of deterministic rules.  The problem here is that `dep` represents a tree structure we've never analyzed before, so there's no best guess to use.

**Comment by jeffrschneider** [comment]
Glad to see the 4 year and 9 day turn around :)

**Comment by AngledLuffa** [comment]
https://www.youtube.com/watch?v=ONFj7AYgbko
