### ISSUE TITLE
PTBTokenizer does not recognize filenames at the end of the input

### ISSUE THREAD

**Issue by gcampax** [stanfordnlp/CoreNLP#622]
PTBTokenizer includes a rule of the form:

{FILENAME}/({SPACE}|[.?!,\"'<])

This is supposed to catch file names or path names in the input and return them as a single token. This unfortunately breaks when the file name is at the end, because the lookahead forces it to have a space or delimiter character afterwards.
As a result, the token is split on slashes and periods, which is incorrect.

(The use case here is to handle chatbot commands of the form "open images/cat.png". In our use case, punctuation is usually inconsistent and/or missing)

**Comment by manning** [comment]
I agree that this behavior is unfortunate, and it would be "good to fix".

However, it is tricky to fix it properly within the constraints of the current architecture. That is: Unlike many other NLP packages, we currently use a highly efficient lexer for tokenization, JFlex, which purely chops off sequences from the front of a character stream. AFAICS, it can't actually use "end of file" as a trailing context to do the same kind of matching here.

And it just doesn't work to not have any trailing context, because then when you get list items without an intervening space (as you do, even in newspapers), like: `4.Compress the chest ` or `2.Heat olive oil in small saucepan`, then you would otherwise get completely bogus tokens like `4.C`, `ompress` and `2.H`, `eat`.

So I know of no good change that we can make to the tokenizer for the case of running just the tokenizer over a potentially large file. However, for the CoreNLP `TokenizerAnnotator` case, where CoreNLP only works on moderately-sized pieces of text anyway, the obvious crude fix would be to just append a space or newline to whatever text it is given to tokenize, so there is always trailing context.

We'll think about doing that for a future release, but we're trying to ramp down necessary fixes for v3.9.0 currently, so I won't muck with that immediately.

However, the same argument suggests a very easy workaround for you -- if you just add a newline to the end of what the user types before passing it to the tokenizer, then the above example should work right!

**Comment by AngledLuffa** [comment]
This was fixed a while back:

8372abecc12d1102072d1d1b2a1452a90866b92d
