### ISSUE TITLE
Adverbs of Orientation

### ISSUE THREAD

**Issue by jeffrschneider** [stanfordnlp/CoreNLP#656]
Most of the adverbs of orientation are tagged incorrectly. Some are showing up as compound nouns, others as adjectives. 

[Adverbs of Orientation.xlsx](https://github.com/stanfordnlp/CoreNLP/files/1860108/Adverbs.of.Orientation.xlsx)

**Comment by J38** [comment]
Thank you for bringing up this issue we will add it to our list of errors.

**Comment by jeffrschneider** [comment]
This is your list of errors. That's what Github Issues literally is - it's your list of errors. You close an issue when the issue has been resolved. The issues your closing have not been resolved. 
@manning

**Comment by J38** [comment]
Hi, I'm going to create an issue for part of speech tagging errors in general.  I will link the issues you've posted to that issue.  Please in the future if you find new examples post those in that thread.  We do like to use the total issue count as a rough sense of the status of the software engineering issues with Stanford CoreNLP.  It is unfortunate that there are part of speech tagging errors, but all of our algorithms are not 100% accurate, due to the fact that NLP tasks like part of speech tagging our not fully solved.  The state of the art algorithms for part of speech tagging are in the range of 97% accuracy, due to limitations in both the algorithms and training data (maybe more so training data?)  So unfortunately to address the issues you bring up, we'd have to engage in active new research on part of speech tagging (which no one here is working on that much), collect new part of speech training data, or possibly build some sort of rules based approach to handle these specific cases you have mentioned.  It is possible in the future as I alluded to on a different issue we may release a next generation system based on deep learning that is tied in with our dependency parsing.  Thank you again for raising these issues though, it is definitely true that the system can make some glaring errors at time.
