### ISSUE TITLE
Clarification on licensing (GPLv3 vs. GPLv2)

### ISSUE THREAD

**Issue by dylon** [stanfordnlp/CoreNLP#662]
Hi,

The licensing section of CoreNLP's documentation states, "in general Stanford NLP code is GPL v2+, but CoreNLP uses several Apache-licensed libraries, and so the composite is v3+".  Does this mean the CoreNLP source and its models are licensed under the GPLv2, but that you must claim the GPLv3 license because some of its transitive dependencies are GPLv3 licensed?  If that's the case, if the GPLv3 licensed dependencies are removed or changed to non-GPLv3 versions, would that mean the transitive dependency closure (including CoreNLP) would then be GPLv2?

Also, what is the difference between the standalone CoreNLP distributions and its main distribution?  I found this issue stating they differ in licensing:

https://github.com/stanfordnlp/CoreNLP/issues/220

**Comment by dylon** [comment]
It's been more than seven months since I asked this, may I have an update?  If nothing can be said about this issue, are there plans to switch to GPLv2-compatible libraries?

**Comment by J38** [comment]
I'm not a lawyer (just a software engineer), so this is no way legal advice or an official answer, but I would assume that if you just use Stanford code and models and excise all of the dependencies that are GPLv3, you would have something that is GPLv2.  I can try to ask Chris to clarify.

The distributions are just subsets of code from the full CoreNLP.  There are no plans to change dependencies, and I doubt we will have the time just for the sake of altering the license.

Out of curiosity, what is the advantage of GPLv2 over GPLv3?

**Comment by dylon** [comment]
Honestly, I'm an engineer for a large tech company that has blacklisted the use of any software licensed under the GPLv3, for reasons the legal team has not disclosed.  We had many internal systems that employed CoreNLP when it was licensed under the GPLv2, but since its adoption of the GPLv3 they've had to either seek alternatives or stick with a much outdated version of the library.  Since CoreNLP is, itself, licensed under the GPLv2 I've argued that by excluding the GPLv3 dependencies and not using any of the affected modules, we could continue using the latest version of the library.

Many of us love CoreNLP and are free software enthusiasts, but work for corporations that fear the license and are therefore unable to use it professionally.  Personally, I'm a fan of the MIT license because I don't really care how people use my software -- I'm just happy that they do.

**Comment by J38** [comment]
Ok I'll pester Chris about this, and see what we can do to help you out!

**Comment by manning** [comment]
Sorry that I never got around to dealing with this! And sorry that this has been creating problems for you. We're happy to have you liking and using CoreNLP.

Okay, here's an answer, which I think is fully correct, but not only am I not a lawyer, but the official position of Stanford is that I'm not authorized to give legal advice to others. :)

All the Stanford CoreNLP Java code is licensed as GPL v2-or-later. We haven't changed our licensing of the code. I've tried to improve the wording of that on the github.io site in a way that should be clearer/better for you (and others). Let me know if it could still be clearer/better. (And for the full story, as it says there, we dual license, so it is also available with a commercial license.) To keep things simple, in general we have also tried to favor "GPL-family" licensed libraries for CoreNLP, hence our use of things like com and java.json.

However, the full CoreNLP release uses Apache v2.0 licensed libraries, and that's where the issue of the composite only being validly usable under GPL v3+ comes in.... Refs: https://www.apache.org/licenses/GPL-compatibility.html , https://www.gnu.org/licenses/license-list.en.html .

There is a potential path to getting rid of these dependencies (replacing joda-time with the Java 8 java.time library should in principle be "straightforward" but would in practice be plenty of work), however, I know of no good replacement for the jollyday library), but not only is there's no current work underway in that direction, but things could easily get worse: Our general intention is to update ejml from the very old version we currently use at some point, but then it would also become Apache licensed....

Nevertheless, using a GPL v2 version is easy. If you just don't use SUTime, then you don't need the two Apache-licensed libraries, and you're good to run things as GPL v2. There is an explicit flag to disable SUTime, but if the joda-time library is not available, it disables itself, so you don't have to do anything. I thought that this would mean that one gets no DATE/TIME NER, but actually, it's slightly better than that since it fails over to our old DATE/TIME NER that preceded SUTime. (But just don't expect too much from that old code!)  

So, for example, this code runs CoreNLP, without error, using just our Java code and the CoreNLP models:

```
java -cp "stanford-corenlp-3.9.2.jar:stanford-corenlp-3.9.2-models.jar" edu.stanford.nlp.pipeline.StanfordCoreNLP -outputFormat text -file input.txt
```

It's just that without the external libraries, you lose various functionalities: You can't get XML output without the XML library, you can't use the shift-reduce parser or sentiment without ejml, and you can't use SUTime without at least joda-time.

Finally, for other releases, it's as @j38 said: several of the standalone distributions (tagger, parser) use either no external libraries, or just GPL 2-licensed ones, and then these complications don't arise.

HTH.

**Comment by AngledLuffa** [comment]
Just to clarify a random comment from very long ago: the shift reduce parser does not use ejml.  The RNN parser does, in case you use that.
