### ISSUE TITLE
How to get the percentage of Data Processed

### ISSUE THREAD

**Issue by ladiesman6969** [stanfordnlp/CoreNLP#695]
How can I the percentage of Data Processed using the Library in Java?

**Comment by J38** [comment]
Could you provide more info about your request ?

**Comment by ladiesman6969** [comment]
I am creating a GUI version of CoreNLP using javaFX.
When the user clicks on "Start processing" button, another thread starts which processes the data. When the user clicks on  the button, a loading gif appears. It would be better if there would be some method to get the percentage of data processed which could be shown instead of that loading gif

**Comment by J38** [comment]
Do you mean percentage of documents processed ?

**Comment by ladiesman6969** [comment]
@J38 yeah

**Comment by ladiesman6969** [comment]
@J38 How to get the percentage of doucuments processed

**Comment by ladiesman6969** [comment]
@J38 ?????

**Comment by J38** [comment]
I'm unfamiliar with javaFX.  How exactly are you calling Stanford CoreNLP in your application.  For instance, when you call it from the command line you get a list of completed documents printed to stdout.  So if your application is using the main() method of StanfordCoreNLP, you could look at wherever stdout is being print and count the occurrences of "Annotating file...done" in the output after each call and divide that by the total documents.

**Comment by ladiesman6969** [comment]
I am actually using the CoreNLP java API. After setting up the pipeline, annotators and the document to be processed, I call the pipeline.annotate method and it works! However, it only shows me the status (things being processed, not Percentage) in the console. Your method seems to be good but it would be better if there was a method which would return a double value (0.0-1.0). That would be better...

**Comment by ladiesman6969** [comment]
@J38 any fix

**Comment by AngledLuffa** [comment]
If you take a look here, you can see the basic problem:

https://github.com/stanfordnlp/CoreNLP/blob/9df1bb11fc55840a10551843a16d50a66cd54b3f/src/edu/stanford/nlp/pipeline/AnnotationPipeline.java#L60

The annotation is done one annotator at a time, not one sentence at a time.  However, we don't know ahead of time how long each annotator will take.  For example, the parser usually takes longer than the pos tagger.  Without knowing that, though, we can't estimate how much time is left.

You might think that if you have run each annotator on a sentence, then move on to the next sentence, we could get a good estimate based on how much text is used.  However, we can't transpose the annotators & sentences ourselves because some of the annotators operate on the entire document at once, such as the coref annotator.

What you could do for your application, since you know which annotators you want to use, is you can operate on one sentence at a time for everything except the coref or other annotators which use the whole document.  Don't forget about multithreading...
