### ISSUE TITLE
Documentation: QuoteAttributionAnnotator not listed with other annotators

### ISSUE THREAD

**Issue by zevdg** [stanfordnlp/CoreNLP#720]
I was looking for a tool to find quote attributions in text.  I scoured https://stanfordnlp.github.io/CoreNLP/ and neither the sidebar nor the [annotators list](https://stanfordnlp.github.io/CoreNLP/annotators.html) mentioned the QuoteAttributionAnnotator.  I eventually stumbled upon https://stanfordnlp.github.io/CoreNLP/quoteattribution.html thanks to Google search.

Is this documentation omission intentional, or simply an oversight?

**Comment by J38** [comment]
Hi I need to make things a little clearer, but really now you should just the `quote` annotator, which by default calls the attribution annotator.  You can shut off quote attribution if you like (since it is more resource demanding that just finding quotes).  I'll add some more stuff to the documentation here:

https://stanfordnlp.github.io/CoreNLP/quote.html

**Comment by J38** [comment]
Also, here is some good Java code using the attribution:

https://github.com/stanfordnlp/CoreNLP/blob/master/itest/src/edu/stanford/nlp/pipeline/QuoteAttributionAnnotatorITest.java
