### ISSUE TITLE
POS tagger assigns wrong tags to Currency symbols

### ISSUE THREAD

**Issue by morvarid21** [stanfordnlp/CoreNLP#724]
I am using CoreNLP POS tagger to identify POS tags of tokens, but it gives me wrong tags for currency signs. For example, for € in this text, "Items under 50€", it says POS = CD (cardinal number), or in this text, "€100 and $300", for € it says POS = NN.

**Comment by J38** [comment]
Hi could you give me more details about how you are using Stanford CoreNLP.
I am observing when I run the default pipeline, the tokenizer is turning the euro symbol into a dollar sign which is properly handled by the part of speech tagger and given a POS tag of $.

So you may need to convert it to $ and then restore it in Java code after the part of speech tagging.

The issue is that the part of speech tagger was trained on data that doesn't have euro symbols in it! 

Are you turning off the normalizeCurrency option in the tokenizer?

**Comment by morvarid21** [comment]
@j38 Thanks for your reply. Yes, I am turning off normalizeCurrency because I need all tokens later in my code. I know that I can use the default pipeline and let it normalize currency symbols, and then use some hacks in the code to restore the original symbol after POS tagging. But I wanted to stay away from that path. BTW, this is not only happening for €. For example, in this text, "Items under 50£", currency symbol £ is also detected as a CD (Cardinal number). It seems POS tagger is not trained on any currency symbol except $ !!!

**Comment by J38** [comment]
Hi, so I'll leave this issue open, because I do think we can potentially address this, but this is basically something that is deficient about our POS tagging right now since as you note there weren't a lot of currency characters in the WSJ training data (or the newer UD data we have).

I can think of several ways to fix this, including retaining the model with some currency symbols added into the training data (maybe this is the best way?) or having the Annotator code make necessary conversions and then convert back so it's invisible to you.  I'll keep you posted, but I'll try to fix this soon!

**Comment by J38** [comment]
Also, we are training some new Python code for tagging and parsing, and I'm not sure if that has a language model component in it...if it does have a language model component, that would presumably capture this issue?  At any rate, I'm probably leaning towards just retraining the model with a variety of currency symbols so it will default work properly.  Thanks!

**Comment by morvarid21** [comment]
Thank you @J38! That would be great!

**Comment by morvarid21** [comment]
@j38 I observed that default pipeline(i.e. NormalizeCurrency is ON) does not normalize all currency symbols, for example, the Yen symbol (¥) is not normalized. Because of this even my workaround, i.e. letting pipeline to normalize and pos tag currency symbols, and restoring symbols after POS tagging, is not working.

How is currency normalization done? What are the limitations? It is really frustrating...

**Comment by J38** [comment]
This is handled in

```
edu.stanford.nlp.process.LexerUtils
```

There is a list of characters to replace.  I am not sure what was behind the decision to not include the Yen symbol in `GENERIC_CURRENCY_PATTERN` on (line 17).  I'll talk it over and see if we should just add more characters to that pattern or if there is a reason to not do it.

I'd still say the best way to resolve this is to retrain a part of speech tagger with the extra currency symbols.  I'll put improving currency symbol handling on my project list!

**Comment by J38** [comment]
Hi could you please give me a list of any currency symbols you'd like handled.  I have pound, euro, and yen on my list.  If you'd like anything else please let me know.  I'm going to add some additional training data where these characters are tagged as "$" part-of-speech tag, and we think this new model should handle this.

**Comment by J38** [comment]
So I add a small list of examples where those three characters are classifier appropriately and re-trained the model.  It was able on some basic examples to correctly mark all of them with the POS tag "$".  The convention I was told to use was "$" for currency part of speech tag.  We are going to continue working on fixing some issues with the part of speech model by adding in some more training data and verifying the new model still has a good quality.

**Comment by morvarid21** [comment]
Thank you @J38! another currency symbol which I've had problem with is Won (₩). Similar to Yen, it is not even normalized.

**Comment by J38** [comment]
Hi here are two updates:

1.) If you build the latest version of the code from GitHub the tokenizer will recognize Rubles and Won.
If you use the `-tokenize.options "normalizeCurrency=false"` , you should see all of these currency symbols properly tokenized and not normalized.

2.) I would appreciate if you could try out an experimental part-of-speech tagging model we have created which is trained to recognize common currency symbols and give them the tag `$`.

It is available at:

http://nlp.stanford.edu/software/english-left3words-distsim-plus-currency.tagger

It is used with `pos.model english-left3words-distsim-plus-currency.tagger`.

Thanks!

**Comment by AngledLuffa** [comment]
btw, these sentences are here:

https://github.com/stanfordnlp/handparsed-treebank/blob/master/english-tagged/english-currency-train.txt
