### ISSUE TITLE
Dependency parser created a weird self-dependency

### ISSUE THREAD

**Issue by a7744hsc** [stanfordnlp/CoreNLP#752]
I am currently using coreNLP for dependency parsing. When I use the function on the following sentence, a word "work" have a dependency on itself on enhanced dependency. I tried it on `corenlp.run` and the issue also shows up.

The sentence:

`Micron does not disclose production capacity of the new phase of the Fab 10, but says that the new plant will require it to hire additional personnel to work at the fab and in the supply chain.`

The issue can be reproduced through  [corenlp.run](http://corenlp.run/), just run this sentence on [corenlp.run](http://corenlp.run/) and the issued will shown in "Enhanced++ Dependencies:"(The `work` word).

**Comment by AngledLuffa** [comment]
If I understand correctly, this is the copy mechanic coming into play.  Consider the sentence:

`He works at the fab and sleeps at home`

Here you would have a `conj_and` dependency between `works` and `sleeps`  

`He works at the fab and at home`

The regular dependencies won't have a `conj_and` dependency here, but the enhanced++ dependencies introduce a "copy" of `works` so that there can now be a `conj_and` dependency from `works` to itself.

**Comment by AngledLuffa** [comment]
@manning wanted to emphasize that this is the copy node mechanic, not an actual self loop.  Apparently it doesn't show up as a copy in the visualization.

Also, when I say the basic dependencies do not have the `conj` dependency, there is a `conj` from `fab` to `home`.  There just isn't a `conj` between the verbs as there is only one verb in the basic dependencies.  The copy is introduced in the ++ form.
