### ISSUE TITLE
Is there a way to provide pre-tokenized sentences while still expect CoreNLP to do PTB-style conversion?

### ISSUE THREAD

**Issue by ZhaofengWu** [stanfordnlp/CoreNLP#755]
For the lexicalalized parser, I can specify both `-tokenized` and `-escaper edu.stanford.nlp.process.PTBEscapingProcessor`. But for the CoreNLP server, if I specify `'tokenize.whitespace': 'true'`, then it looks like `'tokenize.options': 'ptb3Escaping=true'` is ignored. (I am using the [official Python wrapper](https://github.com/stanfordnlp/python-stanford-corenlp))

**Comment by JianLiu91** [comment]
You should set "tokenize.whitespace": True in the `properties`.

**Comment by manning** [comment]
The CoreNLP interfaces don't support the exact equivalent of the `-escaper` from the LexicalizedParser, so there isn't a way to perfectly do this. Already tokenized text is assumed to also be correctly normalized.

However, since from version 4 of CoreNLP, much less escaping of tokens is done by default, there should be much less need for this. Certainly, the things done by `PTBEscapingProcessor` don't need doing. Hence I'm going to call this not a problem that needs solving.
