### ISSUE TITLE
potential bug with collapsed dependencies

### ISSUE THREAD

**Issue by vyhuhol** [stanfordnlp/CoreNLP#76]
Hello,

I am using the recent version of CoreNLP for collapsed dependency parsing with output to json.

with configuration

annotators = tokenize,ssplit,pos,lemma,depparse

It looks like preposition dependencies are not got collapsed in the json output format

for example,  the sentence

"Conduct your  business in the most professional and efficient way."

Doesn't have collapsed dependency.

**Comment by sebschu** [comment]
Since the last release CoreNLP's default dependency representation is [Universal Depencencies](http://universaldependencies.github.io/docs/#language-en) (UD) and one of the differences between Universal Dependencies and Stanford Dependencies (SD) is that prepositions are no longer the head of a prepositional phrase. Therefore there is no need to collapse prepositions as the content word is already a dependent of whatever it modifies. 

In your example, you would have the following partial parse in the Stanford Dependencies representation:

    prep(Conduct-1, in-4)
    pobj(in-4, way-10)

This would be collapsed to:
    prep_in(Conduct-1, way-10)

However, with the Universal Dependencies representation you get the following partial parse:

    case(way-10,  in-4)
    nmod(Conduct-1, way-10)

As you can see, the basic UD representation already contains the relation between `Conduct` and `way`, so doesn't exist anything that could be collapsed.


CoreNLP still has support for Stanford Dependencies. See the [CoreNLP FAQ](http://nlp.stanford.edu/software/corenlp-faq.shtml#originaldeps) for more details.

**Comment by vyhuhol** [comment]
Thank you very much for the detailed answer.

If I understood correctly, there is no way to get "prep" collapsed dependencies with  Stanford Dependencies. 

I didn't get, my settings were
depparse.model = ../CoreNLP/english_SD.gz
parse.originalDependencies = true

**Comment by sebschu** [comment]
You should be able to retrieve them from a sentence annotation using the `SemanticGraphCoreAnnotations.CollapsedDependenciesAnnotation.class` key.

**Comment by vyhuhol** [comment]
Is it possible without using API?
