### ISSUE TITLE
Is it possible to ignore certain phrases while doing tokenization?

### ISSUE THREAD

**Issue by Mo-Talha** [stanfordnlp/CoreNLP#769]
Say I have some text and it contains some phrases that would normally get broken down while doing tokenization. 
For example: "Windows 10" -> 
Windows
10

Is it possible to pass in some options to ignore the phrase "Windows 10" while doing tokenization?
If not, will it be implemented in the future? Any alternatives?

**Comment by J38** [comment]
At this time there is not an option for this.  I'm not sure you want to do this, because in your example "Windows" and "10" are indeed separate tokens.  The issue is that "Windows 10" is an entity composed of the two tokens.  You could use `regexner` to recognize this as an entity (e.g. `OPERATING_SYSTEM`).  See: https://stanfordnlp.github.io/CoreNLP/regexner.html
