### ISSUE TITLE
Less NE's per run

### ISSUE THREAD

**Issue by WillemJan** [stanfordnlp/CoreNLP#83]
There is a bug in the Stanford NLP Library which results in fewer named-entities while processing the same text.

see: https://github.com/WillemJan/Stanford_ner_bugreport

**Comment by manning** [comment]
Sorry that no one looked into this for several months!  Despite the very clear and well documented example - thanks for that!!!

But I can explain this. It's not actually a bug, but I can see it is confusing/worrying.

The long term default of Stanford NER has been that it does a tiny bit of learning on the data that it runs on (so-called "transductive learning"), where here it is merely learning words that appear lowercase in the text it is processing, and then it regards them as less likely to be named entities when seen in places like sentence initially. This actually helps performance! Indeed, it helps here. The text you're using is French, but I presume from the filename that the model is really built for Dutch, and so French words will be generally unknown. So, the first time through, it wrongly tags "Nous" and "Vive" as person names, but it sees that "nous" and "vive" also appears later in the text, so the next time through, it tags them as not names.

So, not a bug!

However, this isn't the first time that this behavior has caused concern or difficulties for people, since a lot of people would like NER to be repeatable with the same output. And it can also be problematic because it causes some growth in the memory needed for the server over time. So, I think I'm going to change the default so that by default the code doesn't do this, and you have to explicitly turn this on.

You can get this behavior now, by using the flag:

    -maxAdditionalKnownLCWords 0

I retried your example with the following command:

    java -mx700m edu.stanford.nlp.ie.NERServer -loadClassifier dutch.gz -port 1234 -maxAdditionalKnownLCWords 0

and I then got the same output each time.  Hope that helps!

**Comment by manning** [comment]
p.s. Just looked at the D-Lib magazine article.  It's cool that you're using it at such a large scale. Do you find the CoNLL 2002 Dutch data sufficient for good performance? I also saw this other article for Dutch: http://www.europeana-newspapers.eu/named-entity-recognition-for-digitised-newspapers/ - but the promised "coming soon" training data doesn't yet seem to have appeared....

**Comment by WillemJan** [comment]
Thanks a lot for helping me find the reason why it happened! I've tested the 'maxAdditionalKnownLCWords' flag, and it works. For our production system we use a small Java wrapper that uses the Stanford library, however setting it via the default property route does not seem to work:

```Properties prop = new Properties();
prop.setProperty("maxAdditionalKnownLCWords", "0");
this.classifier = CRFClassifier.getClassifier(serializedClassifierPath, prop);
```
Maybe I'm doing something wrong here, however, compiling it against a modified version of the Stanford lib where the flag is set to 0 in the source works ;)

Since our OCR is verry noisy at times, we use a combination of CoNLL 2002, and some of the pages tagged in the Europeana newspaper project. http://lab.kbresearch.nl/static/html/eunews.html, I will contact the site owner, and replace the 'comming soon' into the proper link.

**Comment by cneud** [comment]
Thanks for resolving this! 

The blogpost at http://www.europeana-newspapers.eu/named-entity-recognition-for-digitised-newspapers/ now links to the training data and models available at http://lab.kbresearch.nl/static/html/eunews.html.

The training data is also on GitHub: https://github.com/EuropeanaNewspapers/ner-corpora/
