### ISSUE TITLE
POS verb error for the sequence NN,PRP,IN

### ISSUE THREAD

**Issue by neilnelson** [stanfordnlp/CoreNLP#836]
This affected two sentences out of a body of 473.

Sentence: You must find pertinent objects, factor them into classes at the right granularity, define class interfaces and inheritance hierarchies, and establish key relationships among them.

You	PRP
must	MD
find	VB
pertinent	JJ
objects	NNS
,	,
**factor	NN (perhaps VB instead)
them	PRP
into	IN**
classes	NNS
at	IN
the	DT
right	JJ
granularity	NN
,	,
define	VB
class	NN
interfaces	NNS
and	CC
inheritance	NN
hierarchies	NNS
,	,
and	CC
establish	VB
key	JJ
relationships	NNS
among	IN
them	PRP
.	.

Sentence: Chain-of-Responsibility handles requests by forwarding them from one object to another along a chain of objects.

Chain-of-Responsibility	NN
handles	VBZ
requests	NNS
by	IN
**forwarding	NN (perhaps VB? instead)
them	PRP
from	IN**
one	CD
object	NN
to	TO
another	DT
along	IN
a	DT
chain	NN
of	IN
objects	NNS
.	.

**Comment by neilnelson** [comment]
He PRP
is VBZ
**climbing VBG**
the DT
hill NN
. .

He PRP
is VBZ
**forwarding NN (?)**
the DT
mail NN
. .

**Comment by neilnelson** [comment]
This sentence is much the same as the first sentence above with the first two verb phrases exchanged. This causes the VB on 'factor' to appear.

Sentence: You must factor them into classes at the right granularity, find pertinent objects, define class interfaces and inheritance hierarchies, and establish key relationships among them.

You PRP
must MD
factor **VB**
them PRP
into IN
classes NNS
at IN
the DT
right JJ
granularity NN
, ,
find VB
pertinent JJ
objects NNS
, ,
define **VBP** (a minor difference from above)
class NN
interfaces NNS
and CC
inheritance NN
hierarchies NNS
, ,
and CC
establish VB
key JJ
relationships NNS
among IN
them PRP
. .

**Comment by neilnelson** [comment]
For my processing the Stanford Parser output is loaded into MySql tables. Wrote a program to identify sentences with "tokens" having the NN,PRP,IN POS sequence. Further refined the selection for sentences where the "parse" tree parent of NN was VP and there were no tokens to the left of NN under the VP parent. Changed the NN to VB. The additional selection identified only one sentence of the total for this change.

**Comment by neilnelson** [comment]
Found the following three examples out of 538,522 sentences and phrases.

They PRP
should MD
fence **NN (?)** 
it PRP
in IN
. .

Can MD
you PRP
clue **NN (?)**
me PRP
in OM
? .

art NN
produced VBN
by IN
decorating VBG
a DT
surface NN
with IN
cutouts NNS
and CC
then RB
coating **NN (?)**
it PRP
with IN
several JJ
layers NNS
of IN
varnish NN
or CC
lacquer NN

**Comment by AngledLuffa** [comment]
Our recent update to 4.0.0 included a new data source with a bunch of web terms, and that seems to have cleaned up a few of these issues.  For example, the sentences with `forwarding` are now tagged & parsed in a more expected manner.

It's a little unclear from your description whether you were using the parser or just the tagger, but here is a summary of a couple of those issues:

factor: the PCFG parser now knows about factor, but the tagger by itself gets it wrong, so the SR parser subsequently gets it wrong

forwarding now seems to work

climbing_VBG looks correct to me.  

define_VBP as a tagger error is not surprising, since the model used in the java tagger will have a hard time remembering that it originally started the phrase with "must"

fence_NN is still wrong, and it's a little weird, as the tagger should recognize that "should" is a very strong signal for a verb.  however, every instance of fence in the training data is fence_NN, so that's probably an even stronger signal.

clue_NN is still wrong.  same general issue as fence

coating is now correctly tagged as VBG

I'll add a few sentences with the incorrectly tagged words to the training data so that the next generation of models are a little more likely to pick the correct tag.  Thanks for reporting these!
