### ISSUE TITLE
Sentence split

### ISSUE THREAD

**Issue by piotrmwojcik** [stanfordnlp/CoreNLP#870]
Sentence spliting fails on named entity. The following sentence is parsed as one with `Apple Inc.` correctly recognized as named entity.

> Shares of Apple Inc. fell 1.2% to lead Dow decliners after the company unveiled a suite of new products, including its long-awaited video streaming service.

However, the sentence is splited after `Meanwhile, Apple Inc.`
> Meanwhile, Apple Inc. Chief Executive Tim Cook got a 22% raise to $15.7 million in 2018 while the stock fell 6.8%, after getting a 47% raise in 2017 as the stock climbed 46%.

Reproducible on https://corenlp.run/ and with the following code snippet:
```
  val props = new Properties()
  props.setProperty("annotators", "tokenize, ssplit, pos, lemma, ner, parse, dcoref")

  val document1 = new Annotation("Meanwhile, Apple Inc. Chief Executive Tim Cook got a 22% raise to $15.7 million in 2018 while the stock fell 6.8%, after getting a 47% raise in 2017 as the stock climbed 46%.")
  val document2 = new Annotation("Shares of Apple Inc. fell 1.2% to lead Dow decliners after the company unveiled a suite of new products, including its long-awaited video streaming service.")
  val pipeline = new StanfordCoreNLP(props)
  pipeline.annotate(document1)
  pipeline.annotate(document2)
  println(document1.get(classOf[SentencesAnnotation]).asScala.length)
  println(document2.get(classOf[SentencesAnnotation]).asScala.length)
```

**Comment by AngledLuffa** [comment]
Actually, it's the capital letter doing it here I believe.  I don't think you'll be able to fix this using deterministic rules, which is how the java tokenizer & ssplit processors are built.  For example:

He sold his shares of Apple Inc.  Chief Executive Tim Cook made over $...

The stanfordnlp python package has a model which tries to learn sentence boundaries, so that might have some chance of distinguishing the two cases.
