### ISSUE TITLE
Stanford light weight mobile version libraries which takes less heap when NER in pipeline

### ISSUE THREAD

**Issue by luckynarang** [stanfordnlp/CoreNLP#875]

**Comment by AngledLuffa** [comment]
This issue was kind of vague.  The good news is the 4.0.0 release and some changes in master since the release of 4.0.0 have reduced the amount of memory needed to run NER.  It might still be kind of large compared to a phone's memory, though.  You could get some extra savings by turning off various NER features: no fine grained annotation, no sutime, or fewer of the CRF models.
