### ISSUE TITLE
CoreNLP training doesn't work

### ISSUE THREAD

**Issue by NadiaRu** [stanfordnlp/CoreNLP#904]
Hello!
I am trying to train a Stanford CoreNLP model for the French medieval.
I am using this command.
![Capture du 2019-07-10 13-29-55](https://user-images.githubusercontent.com/43485702/60966006-8e63ef00-a317-11e9-8cf8-772d090ec8e6.png)

Unfortunately, I have this result and the CoreNLP doesn't create a new model...
![Capture du 2019-07-10 13-32-32](https://user-images.githubusercontent.com/43485702/60965906-5361bb80-a317-11e9-9806-f0370c18cadf.png)
![Capture du 2019-07-10 13-32-49](https://user-images.githubusercontent.com/43485702/60965907-53fa5200-a317-11e9-8f68-31e3f75032e3.png)
![Capture du 2019-07-10 13-33-06](https://user-images.githubusercontent.com/43485702/60965908-53fa5200-a317-11e9-9b6e-8944518300c0.png)
Could you help me to find the error?

**Comment by manning** [comment]
In the second screenshot, the parser isn't loading any data (trees) and so nothing is learned. There are two possible reasons I can suspect:

1. It fails to load a TreebankLanguagePack. As things stand, you can't use AbstractTreebankLanguagePack, since it is an abstract class. You either need to write your own with an appropriate definition of punctuation, etc. for the language, or to use the nearest to matching one, which might be: `edu.stanford.nlp.trees.international.french.FrenchTreebankLanguagePack`.
1. There's something wrong with the format of the data file and so it fails to load any sentences/trees. This parser at present only works with files in CoNLL-X format. (In particular, it won't read CoNLL-U files; you need to delete any lines starting with hashes (#) and any word ranges or empty nodes. This is something we plan to address in a future release.)

If neither of those things fix the problem, it'd be great if you could send at least a portion of the data which it won't train on....
