### ISSUE TITLE
Protential bug with cached Annotators

### ISSUE THREAD

**Issue by DaveQuinn29** [stanfordnlp/CoreNLP#910]
Good morning -

I think I have found a potential bug in the caching of annotators and/or the property sets used to construct them.

I am using CoreNLP version 3.9.2, and have a server implementation where multiple pipelines are created for different property sets. For some of these pipelines, I am using the relation annotator along with a custom training model that I have created for my domain.

What I find is that an instance of edu.stanford.nlp.pipeline.RelationExtractorAnnotator is constructed when when the relation annotator is requested, but that the Properties used to construct the instance are not the same as the ones specified for that current pipeline.

Here's some code to describe this more clearly:

`
    // perform an annotation without relation annotation
    Properties props = new Properties();
    props.setProperty("annotators",
      "tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie,regexner");

    StanfordCoreNLP pipeline = new StanfordCoreNLP(props);
    pipeline.annotate(new CoreDocument(text)); 

    .
    . // everything is annotated properly
    .

    // perform an annotation with relation annotation and with custom trained model
    props = new Properties();
    props.setProperty("annotators",
      "tokenize,ssplit,pos,lemma,ner,depparse,coref,natlog,openie,regexner,parse,relation");

    props.setProperty("sup.relation.model", "/tmp/MyModel.ser");
    props.setProperty("sup.relation.verbose", "true");

    pipeline = new StanfordCoreNLP(props);
    pipeline.annotate(new CoreDocument(text)); 
    .
    . // edu.stanford.nlp.pipeline.RelationExtractorAnnotator is being 
    . // constructed with the earlier property set,
    . // which does not have the "sup.relation.*" properties,
    . // and even has the earlier annotator list without ,parse,relation
    .
`

I verified that the incorrect properties are being used by inserting some trace code in a local (overridden) copy of RelationExtractorAnnotator to show the properties specified during construction, and to verify the calling stack - both confirm what I have described above. I also performed a similar check in another annotator being used (TokensRegexAnnotator) and I see the same issue (incorrect properties specified during construction).

I also traced AnnotationPool, particularly the "signature" check, and the problem does not seem to be in there.

Lastly, I was able to workaround this problem, albeit with a most unsatisfactory workaround, by invoking StanfordCoreNLP.clearAnnotatorPool() before each new pipeline.annotate(). As this call simply clears the GLOBAL_ANNOTATOR_CACHE, I assume that something is getting improperly cached there.

Can you suggest a more satisfactory workaround?

Thanks in advance for your help -

Dave

**Comment by DaveQuinn29** [comment]
Sorry, meant "AnnotatorPool", not "AnnotationPool".

**Comment by AngledLuffa** [comment]
While I don't have an immediate answer on the best way to fix this, the
core of the problem is that the properties start with "sup.relation" and
the caching only looks at properties starting with "relation".  Ideally
there's some way to add another prefix to the caching.  Alternatively, I
have no idea why "sup.relation" is used instead of "relation", but perhaps
that can be changed.

**Comment by DaveQuinn29** [comment]
Super, John - thanks for that tip. I was able to workaround simply by including a "dummy" property to the pipeline that begins with 'relation', e.g.:

`relation.model = /tmp/MyModel.ser`

Best regards,
dave

**Comment by AngledLuffa** [comment]
That seems perfectly reasonable.

For the future, I made it so that it looks for relation.model instead of
sup.relation.model.  I also kept the old one around (with a loud warning)
so that programs like yours don't stop working.

John

**Comment by victoriastuart** [comment]
I'm going to echo @DaveQuinn29 's concern that there is a cache and/or some other issue in CoreNLP.  I had been trying to add custom NER tagging via a custom TSV regexner file, like I used with the JAVA version a couple of years ago (more recently in Python via stanfordnlp).  I couldn't get regexner to work in Python, so I returned to the JAVA implementation of CoreNLP (from the CLI) to troubleshoot (and work from there, if needed).

```bash
java -Xmx16g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP \
-annotators 'tokenize,ssplit,pos,lemma,regexner' \
-regexner.mapping custom_entities.tsv \
-file input_sentence.txt \
-outputFormat text
```

However, I have not had much success in NER tagging with CoreNLP's trained models plus my custom NER tags file.

```
Victoria	PERSON	ORGANIZATION,CITY	2
Stuart	PERSON	ORGANIZATION,CITY	2
Victoria Stuart	PERSON		2
Yap	PRGE	PERSON	2
p53|p53-mediated	PRGE		2
...
```

I've tried various permutations of `'tokenize, ssplit, pos, lemma, ner, regexner` (in that relative order) with `-regexner.mapping` | `-ner.additional.regexner.mapping` ... and I cannot simultaneously NER tag text with the default CoreNLP libraries plus my own custom NER tags.  I expect the `ner,regexner` annotators combination with `-regexner.mapping` to co-tag with CoreNLP tags, superseded by custom NER tags (is that true, or am I mistaken?).

[I haven't looked at the `rules` approach, [https://stanfordnlp.github.io/CoreNLP/ner.html#regexner-rules-format](https://stanfordnlp.github.io/CoreNLP/ner.html#regexner-rules-format) : my regexner is via a TSV file as described here: https://nlp.stanford.edu/software/regexner.html .]
 
While I can get ***either*** NER (the default statistical model + ... fine NER rules added via the regexner annotator) ***or*** `-regexner.mapping` (with my custom tokens file) to work, it's always either one or the other.  And before I'm directed there (cough: @J38), I've certainly looked at the https://stanfordnlp.github.io/CoreNLP/ner.html page to which we are so often referred.

Furthermore, in evaluating various permutations of annotators, I've found upon stepwise additions adding the `lemma` annotator is particularly troublesome, immediately breaking regexner.   And, when I try to step back, old annotator settings are retained (cached?).  For example, I get lemmatization etc. in the output even if it is not included in the annotators argument list.

It appears that whenever CoreNLP encounters an error, it silently loads the defaults, so that user-defined settings are ignored.
