### ISSUE TITLE
POS tagging error for "strong #2" "clear #2" "solid #2" etc.

### ISSUE THREAD

**Issue by bnomis** [stanfordnlp/CoreNLP#913]
Sentence involving the sequence JJ-#-CD sometime incorrectly assign "," where it should be CD. 

For example the sentence:

```Yes, we -- I think that was some contract wins we expect to actually be a solid #2 in the market.```

Tags as:

```
solid = JJ
# = #
2 = ,
```

If I change the "2" to a "3". It's correct:

```
solid = JJ
# = #
3 = CD
```

This only happens with `#2` any other integer works find.

I've attached some example sentences demonstrating the effect.

[unknown-tag-hash2.txt](https://github.com/stanfordnlp/CoreNLP/files/3394809/unknown-tag-hash2.txt)

**Comment by gamer01** [comment]
I am not sure if its clear to you how this model is trained, but its quite expected, that a Machine Learning tagger will do errors. There is no way to fix single classification errors, as it would effect the classification of all other tags as well.

As long as this errors are not systematic, i think you should not expect that the developers do anything about it. At a 3% errorrate and 60% sentence accuracy it is obvious that you will find examples where tags are assigned erroneous.

**Comment by AngledLuffa** [comment]
Weirdly there is a training example in the penn treebank WSJ data which has this bug:

```
Britain_NNP 's_POS current_JJ account_NN deficit_NN dropped_VBD to_TO #_# 1.6_CD billion_CD -LRB-_-LRB- $_$ 2.56_CD billion_CD -RRB-_-RRB- in_IN September_NNP from_IN an_DT adjusted_JJ #_# 2_, billion_CD -LRB-_-LRB- $_$ 3.21_CD billion_CD -RRB-_-RRB- the_DT previous_JJ month_NN ,_, but_CC the_DT improvement_NN comes_VBZ amid_IN increasing_VBG concern_NN that_IN a_DT recession_NN could_MD strike_VB the_DT U.K._NNP economy_NN next_JJ year_NN ._.
```

In fact this is the only example of the pattern ???_JJ #_# 2_??? in the WSJ data, so it's not surprising that it then treats any such context with this incorrect tag.  So in some sense, the tagger is doing the right thing!

Obviously this is suboptimal though.  What we can do is throw a couple of these examples in the training data for the tagger so that future models are more likely to get it right.  

```
During_IN this_DT time_NN ,_, we_PRP 've_VBP gone_VBN from_IN #_# 4_CD to_TO a_DT clear_JJ #_# 2_CD market_NN share_NN player_NN in_IN network_NN storage_NN ._.
We_PRP have_VBP been_VBN a_DT good_JJ #_# 2_CD player_NN in_IN the_DT U.K._NNP animal_NN health_NN market_NN for_IN a_DT while_NN ,_, several_JJ years_NNS ._.
We_PRP 're_VBP already_RB more_JJR than_IN twice_RB as_RB big_JJ as_IN IBM_NNP ,_, the_DT current_JJ #_# 2_CD player_NN in_IN the_DT database_NN business_NN ._.
```

Presumably 3 such examples will overrule the 1 incorrect example from the original WSJ data.  Next time the model gets rebuilt, it will hopefully get your examples correct.
