### ISSUE TITLE
What are the EnglishGrammatical classes ?

### ISSUE THREAD

**Issue by AlexisPister** [stanfordnlp/CoreNLP#924]
Hello,

I am using a software (clausIE) based on stanfordNLP, which use the edu.stanford.nlp.trees.EnglishGrammaticalRelations and
edu.stanford.nlp.trees.EnglishGrammaticalStructure classes. However, I would like to transpose this software in french, but I did not find any equivalent of those classes. What are those classes for and how could I transpose them in french, if it does not exist already ?

Moreover, in the stanford-parser-models.jar, what are the differences between the englishFactored and englishPCFG models ? Could the frenchFactored model be used as a substitute of the englishPCFG model ?

Finally, I am using stanfordNLP 2.0.4, is the doc or any resource accessible online ?

Thanks

@gatemezing

**Comment by AngledLuffa** [comment]
The EnglishGrammaticalRelations are part of a conversion tool that converts
Penn Treebank style parses to Stanford Dependencies.  There is no such
equivalent for French.

However, Stanford Dependencies evolved into something called Universal
Dependencies, and for this there is a French version:

https://universaldependencies.org/fr/index.html

French CoreNLP supports this (look for French):

https://stanfordnlp.github.io/CoreNLP/index.html#download

We also have a python model which produces those:

 https://stanfordnlp.github.io/stanfordnlp/models.html

Ultimately it will require some reprogramming to make the tool you are
using compatible with French UD, since some of the dependency names are
different from Stanford Dependencies and obviously the languages have
different syntax.  Good luck!

If the included documentation for CoreNLP 2.0.4 is not sufficient, you can
find more on the 4th floor of the Museum of Natural History in NYC.

**Comment by gatemezing** [comment]
Many thanks for the detailed answer. @AlexisPister will probably come back to you with a more precise answer.  
"If the included documentation for CoreNLP 2.0.4 is not sufficient, you can
find more on the 4th floor of the Museum of Natural History in NYC." - Is it irony or a real suggestion to visit NYC? 
BTW, I used the demo tool http://nlp.stanford.edu:8080/sentiment/rntnDemo.html for sentiment analysis and the result is not quite positive :)

**Comment by AngledLuffa** [comment]
What do you mean by "not quite positive"?

My suggestion to visit the fossils exhibit is not a serious suggestion for how to get more documentation for a version 7 years old :)

**Comment by gatemezing** [comment]
"Not quite positive" - I mean it didn't sound like a not serious suggestion. 
Sure, it is a 7 years old documentation used in a tool that we want to improve.. so the question here.

**Comment by AngledLuffa** [comment]
> used in a tool that we want to improve

Well, that is why I suggested trying the French Universal Dependencies,
since you seem to want to use the tool on French.  It will require some
conversion to use the new dependency names, since they aren't exact matches
with the English Stanford Dependencies.
