### ISSUE TITLE
tokenisation problem with underscore words in new release

### ISSUE THREAD

**Issue by mohitvaidya** [stanfordnlp/CoreNLP#942]
In new release of core-nlp it is splitting words on underscore as well, which was not the case with earlier version.
e.g.: Parent_in_law will be splitted as "Mother", "_", "in", "_",  "Law",  is there a way to avoid this.
It is also creating ambiguity with dependency parser since now parser is reading "_" as a separate token.
![image](https://user-images.githubusercontent.com/20730799/63833349-73fdd780-c990-11e9-8656-140ada6cca86.png)

**Comment by mohitvaidya** [comment]
Is it possible to avoid this by using custom annotators !

**Comment by manning** [comment]
This was indeed a regression in v. 3.9.2. It will be fixed in the next release.

If you made your own tokenizer - or took the CoreNLP ones from a previous release and modified them with different class names - then you should indeed be able to use them instead as a custom annotator, though you'd probably also need to specify `-enforceRequirements false` for the system to be happy.
