### ISSUE TITLE
Sentence Splitter Fails with Arabic Input

### ISSUE THREAD

**Issue by Zoidmania** [stanfordnlp/CoreNLP#968]
I'm trying to run the Sentence splitter and tokenizer on unstructured Arabic text. It seems to be failing to detect quite a few sentence boundaries, resulting in larger-than-a-sentence splits that ruin further parser operations.

The regex string in the properties file seems to be ignored, or not totally relied on; I'm not sure what I'm doing wrong. The only thing different in my properties file from the default one is the removal of `pos.models` and `parse.models` declarations, and their associated annotators.

All of the input is UTF-8.

My system:

```bash
$ java -version
openjdk version "14-ea" 2020-03-17
OpenJDK Runtime Environment (build 14-ea+18-Ubuntu-1)
OpenJDK 64-Bit Server VM (build 14-ea+18-Ubuntu-1, mixed mode, sharing)
```

I have the following jars in this directory:

```
protobuf.jar
stanford-arabic-corenlp-2018-10-05-models.jar
stanford-corenlp-3.9.2.jar
stanford-corenlp-3.9.2-javadoc.jar
stanford-corenlp-3.9.2-models.jar
stanford-corenlp-3.9.2-sources.jar
StanfordCoreNLP-arabic-noparse.properties
StanfordCoreNLP-arabic.properties
stanford-english-corenlp-2018-10-05-models.jar
stanford-english-kbp-corenlp-2018-10-05-models.jar
```

My command:

```bash
$ java -mx8g -cp "*" edu.stanford.nlp.pipeline.StanfordCoreNLP \
  -props StanfordCoreNLP-arabic-noparse.properties \
  -file test.txt \
  -outputFormat json \
  -outputExtension .json
```

My properties file:
```
# Pipeline options
annotators = tokenize, ssplit

# segment
#customAnnotatorClass.segment = edu.stanford.nlp.pipeline.ArabicSegmenterAnnotator
tokenize.language = ar
segment.model = edu/stanford/nlp/models/segmenter/arabic/arabic-segmenter-atb+bn+arztrain.ser.gz

# sentence split
ssplit.boundaryTokenRegex = [.]|[!?]+|[!\u061F]+
```

My test input and output:

[test.txt](https://github.com/stanfordnlp/CoreNLP/files/3863977/test.txt)
[test.txt.json.txt](https://github.com/stanfordnlp/CoreNLP/files/3863980/test_parsed.txt)

**Comment by AngledLuffa** [comment]
For whatever reason, the Arabic tokenizer is leaving "2002." or ")." as one
token, which then doesn't get recognized as one of the sentence boundary
tokens by the sentence splitter.  I'll see if I can figure this one out next

**Comment by AngledLuffa** [comment]
I know actual nothing about Arabic aside from it going right to left, so
some guidance on how to fix the tokenizer would be of assistance.

In case this winds up being left for posterity to fix, the file in question
is international/arabic/process/ArabicLexer.flex

--------------------

2002.

There's a rule in the tokenizer which goes like this:

DIGIT = [:digit:]|[\u0660-\u0669\u06F0-\u06F9]
DIGITS = {DIGIT}+
NUMBER = ({DIGITS}[_\-,\+/\\\.\u066B\u066C\u060C\u060D]*)+

This matches 2002. such as in your text, meaning the "." won't be parsed.
In English it would be a safe assumption that if someone writes "I was 24
back in 2002." they absolutely mean the "." to be a stop, and the 2002 is a
number which would not be followed by "." unless the "." was then followed
by more digits.  However, whoever wrote this allowed for things like 2002+
to be a single token.  I'm not even sure that should be the case in
English.  "2002" and "+" would be fine as separate tokens.

I would consider rewriting this as:

NUMBER = {DIGITS}([_\-,\+/\\\.\u066B\u066C\u060C\u060D]+{DIGITS})+

This will match most of the things that the first one matched, except
digits by themselves will be reported as DIGITS instead of NUMBER and the
trailing punctuation will be chopped off.  One could also possibly put at
the end of it something which captures "+" or other similar characters if
that's desirable.

-----------------------

).  and ».


The rules in question here are:

ARPUNC = [\u0600-\u060D\u061B-\u061F\u066A-\u066D\u06D4]
LATINPUNC =
[\u0021-\u002F\u003A-\u0040\u005B-\u0060\u007B-\u007E\u00A1-\u00BF\u2010-\u2027\u2030-\u205E\u20A0-\u20B5\u2E2E]
PUNC = ({ARPUNC}|{LATINPUNC})+

The sideways quote is u00BB, which gets eaten by  \u00A1-\u00BF, and period
is \u002e.  So any number of these in a row will be treated as a single
token.  That doesn't quite seem right.  We can separate out the .!? and
leave the rest as one block, perhaps.

Can you think of any situations where these changes would backfire and
separate tokens that should have been together?

**Comment by AngledLuffa** [comment]
I checked in what is hopefully a satisfactory solution for separating the
sentence final punctuation from the rest of the text.
