### ISSUE TITLE
wrong POS for "bear"

### ISSUE THREAD

**Issue by uniquer4ven** [stanfordnlp/CoreNLP#995]
Hi, in all (or nearly all) instances the verb bear was identified as a noun, e.g. in sentences a la "...PERSON and PERSON bear witness to ..." or "... it was hard to bear ...".
As I am looking for animals this is incredibly annoying, as you might imagine. Is that some tweaking problem or is that on your part?

Code was like this, version is 3.9.2:
`Annotation document = new Annotation(line);
pipeline.annotate(document);
List<CoreMap> sentences = document.get(SentencesAnnotation.class);
for (CoreMap sentence : sentences) {
	for (CoreLabel token : sentence.get(TokensAnnotation.class)) {
	String pos = token.get(PartOfSpeechAnnotation.class);
        }
}`

**Comment by AngledLuffa** [comment]
We actually have a couple training examples with the phrase "bear witness"
correctly labeled.  However, the next version will have a more training
data in the parsers, so if you can bear it for a little while, some of the
problems dogging you may be gone then.  If you're not already using the
beam SR parser, that might also bear some fruit.  Otherwise, I egret to
tell you there isn't much we can do.

**Comment by AngledLuffa** [comment]
Obviously it took us a while longer than we originally hoped, but the new version is almost prepared and it correctly tags a few examples of "bear":

```
I cannot bear it any longer .
It was hard to bear the quarantine .
```
